Data DashBoard Missing Value Mitigation Logs
Imputation Instructions:
 
Impute NA: 
Channel Tested       
Language Tested        
Question Category
 
Missing Dates: Using Date Windows to fill data
Type of Q removed
Sprint / Cycle removed
Change all Build/Version values into 0.1
Channel Tested Normalization
Question ID removed
 
SAVED: Checkpoint2
 
7. Normalize SLA Status
8. Remove Translation Error Type
9. Normalize 12,13,14,15,16,18,19

In [ ]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("My version(TestLog) - Test Log_1.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5547 entries, 0 to 5546
Data columns (total 81 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5516 non-null   object
 1   Test Date                                5299 non-null   object
 2   Tester Name                              5302 non-null   object
 3   Type of Question                         4071 non-null   object
 4   Build / Version                          5287 non-null   object
 5   Sprint / Cycle                           5256 non-null   object
 6   Channel Tested                           5244 non-null   object
 7   Language Tested                          5274 non-null   object
 8   Question ID                              5013 non-null   object
 9   Query Text (Original)                    5259 non-null   object
 10  Question Category                        5100 non-null   object
 11  Time Question Asked (HH:MM:SS)           5083 non-null   object
 12  Time Answer Received (HH:MM:SS)          4115 non-null   object
 13  Response Time (mins) [Auto]              3735 non-null   object
 14  SLA Status                               4360 non-null   object
 15  Question in Review Model?                4436 non-null   object
 16  Question Correctly Framed?               4563 non-null   object
 17  Original Language                        4678 non-null   object
 18  Translated Language                      4377 non-null   object
 19  Translation Quality                      3767 non-null   object
 20  Translation Error Type                   3367 non-null   object
 21  Tagging                                  2591 non-null   object
 22  Allocated to Reviewer?                   2521 non-null   object
 23  Author's Name                            3062 non-null   object
 24  Author Assignment Time                   892 non-null    object
 25  Author Completion Time                   843 non-null    object
 26  Author TAT (mins) [Auto]                 799 non-null    object
 27  Reviewer1 Name                           1081 non-null   object
 28  Reviewer1 Assignment Time                880 non-null    object
 29  Reviewer1 Completion Time                836 non-null    object
 30  Review1 TAT (mins) [Auto]                794 non-null    object
 31  Reviewer2 Name                           1081 non-null   object
 32  Reviewer2 Assignment Time                880 non-null    object
 33  Reviewer2 Completion Time                836 non-null    object
 34  Review2 TAT (mins) [Auto]                794 non-null    object
 35  Reviewer3 Name                           1058 non-null   object
 36  Reviewer3 Assignment Time                880 non-null    object
 37  Reviewer3 Completion Time                833 non-null    object
 38  Review3 TAT (mins) [Auto]                792 non-null    object
 39  Reviewer4 Name                           26 non-null     object
 40  Reviewer4 Assignment Time                24 non-null     object
 41  Reviewer4 Completion Time                22 non-null     object
 42  Review4 TAT (mins) [Auto]                21 non-null     object
 43  Reviewer5 Name                           13 non-null     object
 44  Reviewer5 Assignment Time                12 non-null     object
 45  Reviewer5 Completion Time                12 non-null     object
 46  Review5 TAT (mins) [Auto]                12 non-null     object
 47  Moderator's Name                         920 non-null    object
 48  Moderator Assignment Time                444 non-null    object
 49  ModeratorCompletion Time                 871 non-null    object
 50  Moderator TAT (mins) [Auto]              825 non-null    object
 51  Follow-up Q in Review Model?             2094 non-null   object
 52  Answer Scientifically Correct?           3950 non-null   object
 53  Expert Name Displayed?                   3780 non-null   object
 54  Correct Expert Name?                     3741 non-null   object
 55  Source Links Provided?                   3777 non-null   object
 56  120-min Msg Shown to User?               2318 non-null   object
 57  Notification Received?                   2158 non-null   object
 58  Notification on Same Thread?             1392 non-null   object
 59  Notification Linked Correct Q-ID?        930 non-null    object
 60  Voice Input Working?                     2875 non-null   object
 61  Voice Output Working?                    2854 non-null   object
 62  Voice Input Quality                      2902 non-null   object
 63  Voice Output Quality                     2853 non-null   object
 64  Voice Issue Description                  2074 non-null   object
 65  Weather Q Answered Correctly?            176 non-null    object
 66  Mandi Price Q Correct?                   163 non-null    object
 67  Scheme Q Correct?                        66 non-null     object
 68  Question Saved in DB?                    3850 non-null   object
 69  Answer Saved in DB?                      3530 non-null   object
 70  Q-ID Consistent Across Systems?          3557 non-null   object
 71  WhatsApp vs Web Answer Match?            1675 non-null   object
 72  Overall Test Status                      3750 non-null   object
 73  Defect Severity                          3197 non-null   object
 74  Defect ID / Bug Ref
Zoho Desk Ticketing  1706 non-null   object
 75  Reviewer Remarks                         4225 non-null   object
 76  Tester Remarks                           4251 non-null   object
 77  Status                                   3675 non-null   object
 78  Unnamed: 78                              1 non-null      object
 79  Unnamed: 79                              0 non-null      float64
 80  Unnamed: 80                              1 non-null      object
dtypes: float64(1), object(80)
memory usage: 3.4+ MB

In [3]:
df.drop(columns=df.columns[-3:], inplace=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5547 entries, 0 to 5546
Data columns (total 78 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5516 non-null   object
 1   Test Date                                5299 non-null   object
 2   Tester Name                              5302 non-null   object
 3   Type of Question                         4071 non-null   object
 4   Build / Version                          5287 non-null   object
 5   Sprint / Cycle                           5256 non-null   object
 6   Channel Tested                           5244 non-null   object
 7   Language Tested                          5274 non-null   object
 8   Question ID                              5013 non-null   object
 9   Query Text (Original)                    5259 non-null   object
 10  Question Category                        5100 non-null   object
 11  Time Question Asked (HH:MM:SS)           5083 non-null   object
 12  Time Answer Received (HH:MM:SS)          4115 non-null   object
 13  Response Time (mins) [Auto]              3735 non-null   object
 14  SLA Status                               4360 non-null   object
 15  Question in Review Model?                4436 non-null   object
 16  Question Correctly Framed?               4563 non-null   object
 17  Original Language                        4678 non-null   object
 18  Translated Language                      4377 non-null   object
 19  Translation Quality                      3767 non-null   object
 20  Translation Error Type                   3367 non-null   object
 21  Tagging                                  2591 non-null   object
 22  Allocated to Reviewer?                   2521 non-null   object
 23  Author's Name                            3062 non-null   object
 24  Author Assignment Time                   892 non-null    object
 25  Author Completion Time                   843 non-null    object
 26  Author TAT (mins) [Auto]                 799 non-null    object
 27  Reviewer1 Name                           1081 non-null   object
 28  Reviewer1 Assignment Time                880 non-null    object
 29  Reviewer1 Completion Time                836 non-null    object
 30  Review1 TAT (mins) [Auto]                794 non-null    object
 31  Reviewer2 Name                           1081 non-null   object
 32  Reviewer2 Assignment Time                880 non-null    object
 33  Reviewer2 Completion Time                836 non-null    object
 34  Review2 TAT (mins) [Auto]                794 non-null    object
 35  Reviewer3 Name                           1058 non-null   object
 36  Reviewer3 Assignment Time                880 non-null    object
 37  Reviewer3 Completion Time                833 non-null    object
 38  Review3 TAT (mins) [Auto]                792 non-null    object
 39  Reviewer4 Name                           26 non-null     object
 40  Reviewer4 Assignment Time                24 non-null     object
 41  Reviewer4 Completion Time                22 non-null     object
 42  Review4 TAT (mins) [Auto]                21 non-null     object
 43  Reviewer5 Name                           13 non-null     object
 44  Reviewer5 Assignment Time                12 non-null     object
 45  Reviewer5 Completion Time                12 non-null     object
 46  Review5 TAT (mins) [Auto]                12 non-null     object
 47  Moderator's Name                         920 non-null    object
 48  Moderator Assignment Time                444 non-null    object
 49  ModeratorCompletion Time                 871 non-null    object
 50  Moderator TAT (mins) [Auto]              825 non-null    object
 51  Follow-up Q in Review Model?             2094 non-null   object
 52  Answer Scientifically Correct?           3950 non-null   object
 53  Expert Name Displayed?                   3780 non-null   object
 54  Correct Expert Name?                     3741 non-null   object
 55  Source Links Provided?                   3777 non-null   object
 56  120-min Msg Shown to User?               2318 non-null   object
 57  Notification Received?                   2158 non-null   object
 58  Notification on Same Thread?             1392 non-null   object
 59  Notification Linked Correct Q-ID?        930 non-null    object
 60  Voice Input Working?                     2875 non-null   object
 61  Voice Output Working?                    2854 non-null   object
 62  Voice Input Quality                      2902 non-null   object
 63  Voice Output Quality                     2853 non-null   object
 64  Voice Issue Description                  2074 non-null   object
 65  Weather Q Answered Correctly?            176 non-null    object
 66  Mandi Price Q Correct?                   163 non-null    object
 67  Scheme Q Correct?                        66 non-null     object
 68  Question Saved in DB?                    3850 non-null   object
 69  Answer Saved in DB?                      3530 non-null   object
 70  Q-ID Consistent Across Systems?          3557 non-null   object
 71  WhatsApp vs Web Answer Match?            1675 non-null   object
 72  Overall Test Status                      3750 non-null   object
 73  Defect Severity                          3197 non-null   object
 74  Defect ID / Bug Ref
Zoho Desk Ticketing  1706 non-null   object
 75  Reviewer Remarks                         4225 non-null   object
 76  Tester Remarks                           4251 non-null   object
 77  Status                                   3675 non-null   object
dtypes: object(78)
memory usage: 3.3+ MB

In [5]:
df.head(5)

,Test ID,Test Date,Tester Name,Type of Question,Build / Version,Sprint / Cycle,Channel Tested,Language Tested,Question ID,Query Text (Original),...,Question Saved in DB?,Answer Saved in DB?,Q-ID Consistent Across Systems?,WhatsApp vs Web Answer Match?,Overall Test Status,Defect Severity,Defect ID / Bug Ref\nZoho Desk Ticketing,Reviewer Remarks,Tester Remarks,Status
0,1,08-Jun-26,Souvik Roy,NaN,0.1,NIL,Web App,English,1f16318c-9102-683c-8005-3bbd319b092f,How to control Dila in Paddy?,...,Duplicate,Duplicate,Successfully Identified as Duplicate,NaN,Pass,Low,https://desk.zoho.in/agent/annamai/annam-ai/ti...,NIL,"District names appeared as ""ALL"", it should ha...",NaN
1,2,08-06-2026,Nimisha,NaN,0.1,NIL,Web App,English,1f163288-99fc-62cf-8005-31d3e7adec03,What are the primary causes of stunted growth ...,...,Duplicate,Duplicate,Successfully Identified as Duplicate,NaN,Pass,NO Defect,NaN,NIL,"for longer text, audio output takes more time",NaN
2,Project: Agri Advisory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Duplicate,Duplicate,Successfully Identified as Duplicate,NaN,Pass,NO Defect,NaN,NIL,Its correct,NaN
3,TL-0005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Successfully Identified as Duplicate,NaN,NaN,NaN,NaN,NIL,NaN,NaN
4,TL-0006,NaN,NaN,NaN,NaN,NIL,NaN,NaN,NaN,NaN,...,NaN,NaN,Successfully Identified as Duplicate,NaN,NaN,NaN,NaN,NIL,NaN,NaN

In [6]:
# Taking only those rows that we are sure to contain complete info
# i.e. query_text

import pandas as pd

# Drops rows where the value in 'column_name' is missing
df.dropna(subset=['Query Text (Original)'], inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5259 entries, 0 to 5523
Data columns (total 78 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5259 non-null   object
 1   Test Date                                5257 non-null   object
 2   Tester Name                              5258 non-null   object
 3   Type of Question                         4046 non-null   object
 4   Build / Version                          5249 non-null   object
 5   Sprint / Cycle                           5197 non-null   object
 6   Channel Tested                           5211 non-null   object
 7   Language Tested                          5240 non-null   object
 8   Question ID                              5012 non-null   object
 9   Query Text (Original)                    5259 non-null   object
 10  Question Category                        5095 non-null   object
 11  Time Question Asked (HH:MM:SS)           5082 non-null   object
 12  Time Answer Received (HH:MM:SS)          4114 non-null   object
 13  Response Time (mins) [Auto]              3724 non-null   object
 14  SLA Status                               4348 non-null   object
 15  Question in Review Model?                4419 non-null   object
 16  Question Correctly Framed?               4551 non-null   object
 17  Original Language                        4663 non-null   object
 18  Translated Language                      4364 non-null   object
 19  Translation Quality                      3758 non-null   object
 20  Translation Error Type                   3321 non-null   object
 21  Tagging                                  2587 non-null   object
 22  Allocated to Reviewer?                   2509 non-null   object
 23  Author's Name                            3059 non-null   object
 24  Author Assignment Time                   892 non-null    object
 25  Author Completion Time                   843 non-null    object
 26  Author TAT (mins) [Auto]                 799 non-null    object
 27  Reviewer1 Name                           1081 non-null   object
 28  Reviewer1 Assignment Time                880 non-null    object
 29  Reviewer1 Completion Time                836 non-null    object
 30  Review1 TAT (mins) [Auto]                794 non-null    object
 31  Reviewer2 Name                           1081 non-null   object
 32  Reviewer2 Assignment Time                880 non-null    object
 33  Reviewer2 Completion Time                836 non-null    object
 34  Review2 TAT (mins) [Auto]                794 non-null    object
 35  Reviewer3 Name                           1058 non-null   object
 36  Reviewer3 Assignment Time                880 non-null    object
 37  Reviewer3 Completion Time                833 non-null    object
 38  Review3 TAT (mins) [Auto]                792 non-null    object
 39  Reviewer4 Name                           26 non-null     object
 40  Reviewer4 Assignment Time                24 non-null     object
 41  Reviewer4 Completion Time                22 non-null     object
 42  Review4 TAT (mins) [Auto]                21 non-null     object
 43  Reviewer5 Name                           13 non-null     object
 44  Reviewer5 Assignment Time                12 non-null     object
 45  Reviewer5 Completion Time                12 non-null     object
 46  Review5 TAT (mins) [Auto]                12 non-null     object
 47  Moderator's Name                         920 non-null    object
 48  Moderator Assignment Time                444 non-null    object
 49  ModeratorCompletion Time                 871 non-null    object
 50  Moderator TAT (mins) [Auto]              825 non-null    object
 51  Follow-up Q in Review Model?             2089 non-null   object
 52  Answer Scientifically Correct?           3946 non-null   object
 53  Expert Name Displayed?                   3775 non-null   object
 54  Correct Expert Name?                     3737 non-null   object
 55  Source Links Provided?                   3773 non-null   object
 56  120-min Msg Shown to User?               2314 non-null   object
 57  Notification Received?                   2156 non-null   object
 58  Notification on Same Thread?             1390 non-null   object
 59  Notification Linked Correct Q-ID?        929 non-null    object
 60  Voice Input Working?                     2863 non-null   object
 61  Voice Output Working?                    2849 non-null   object
 62  Voice Input Quality                      2887 non-null   object
 63  Voice Output Quality                     2848 non-null   object
 64  Voice Issue Description                  2069 non-null   object
 65  Weather Q Answered Correctly?            176 non-null    object
 66  Mandi Price Q Correct?                   163 non-null    object
 67  Scheme Q Correct?                        66 non-null     object
 68  Question Saved in DB?                    3838 non-null   object
 69  Answer Saved in DB?                      3527 non-null   object
 70  Q-ID Consistent Across Systems?          3427 non-null   object
 71  WhatsApp vs Web Answer Match?            1674 non-null   object
 72  Overall Test Status                      3746 non-null   object
 73  Defect Severity                          3195 non-null   object
 74  Defect ID / Bug Ref
Zoho Desk Ticketing  1705 non-null   object
 75  Reviewer Remarks                         4077 non-null   object
 76  Tester Remarks                           4248 non-null   object
 77  Status                                   3604 non-null   object
dtypes: object(78)
memory usage: 3.2+ MB

In [8]:
#set Actual values for the dates

import pandas as pd

# Sample data with British formatted dates and some incorrect entries
df

# Convert the column values to datetime using British format (Day First)
# Any incorrect/invalid dates will be turned into NaT
df['Test Date'] = pd.to_datetime(df['Test Date'], dayfirst=True, errors='coerce')

print(df.head(5))

   Test ID  Test Date       Tester Name Type of Question Build / Version  \
0        1 2026-06-08        Souvik Roy              NaN             0.1
1        2 2026-06-08           Nimisha              NaN             0.1
5  TL-0007 2026-06-08  T.Vishnu Vardhan              NaN             0.1
7  TL-0009 2026-06-09           JOYDEEP              NaN             0.1
8  TL-0010 2026-06-09          JOYDEEP               NaN             0.1

  Sprint / Cycle Channel Tested Language Tested  \
0            NIL        Web App         English
1            NIL        Web App         English
5            NIL        Web App         English
7            NIL           BOTH         English
8            NIL           BOTH         English

                              Question ID  \
0    1f16318c-9102-683c-8005-3bbd319b092f
1    1f163288-99fc-62cf-8005-31d3e7adec03
5  1f1646aa-6b75-6c40-80a6-c4c0a58e552f\n
7    1f163c33-2eb6-624d-8005-e22d3237d7f8
8    1f163c43-7d19-6a7d-8005-f8bfaddeefc6

                               Query Text (Original)  ...  \
0                      How to control Dila in Paddy?  ...
1  What are the primary causes of stunted growth ...  ...
5  Which varieties of chilli are most suitable fo...  ...
7  What is the correct method and procedure for p...  ...
8  What is the appropriate application and benefi...  ...

  Question Saved in DB? Answer Saved in DB?  \
0             Duplicate           Duplicate
1             Duplicate           Duplicate
5                   NaN                 NaN
7                 Saved               Saved
8                   NaN                 NaN

        Q-ID Consistent Across Systems? WhatsApp vs Web Answer Match?  \
0  Successfully Identified as Duplicate                           NaN
1  Successfully Identified as Duplicate                           NaN
5  Successfully Identified as Duplicate                           NaN
7  Successfully Identified as Duplicate                           Yes
8  Successfully Identified as Duplicate                           NaN

  Overall Test Status Defect Severity  \
0                Pass             Low
1                Pass       NO Defect
5                 NaN             NaN
7                Pass             NaN
8                 NaN             NaN

            Defect ID / Bug Ref\nZoho Desk Ticketing Reviewer Remarks  \
0  https://desk.zoho.in/agent/annamai/annam-ai/ti...              NIL
1                                                NaN              NIL
5                                                NaN              NIL
7                                                NaN              NIL
8                                                NaN              NIL

                                      Tester Remarks Status
0  District names appeared as "ALL", it should ha...    NaN
1      for longer text, audio output takes more time    NaN
5                         2 hours disclaimer is seen    NaN
7  District names appeared as "ALL", it should ha...    NaN
8                                                NaN    NaN

[5 rows x 78 columns]

/tmp/ipykernel_1790/3952914216.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Test Date'] = pd.to_datetime(df['Test Date'], dayfirst=True, errors='coerce')

In [9]:
#Date Imputation through Bands
import pandas as pd
import numpy as np

df2 = df
# Sample Data: Employee dates with some missing (NaT) or broken sequences

# 1. Ensure data is sorted by employee and date
df2 = df2.sort_values(['Test Date']).reset_index(drop=True)

# 2. Calculate the difference between consecutive dates
# We fill NaT temporarily with the previous value so it doesn't break the continuity check
temp_dates = df2['Test Date'].ffill()
date_diff = temp_dates.diff()

# 3. Define a boundary: A new window starts if the gap is greater than 1 day
# (or if it's the start of a new employee)
new_window_condition = (date_diff > pd.Timedelta(days=1))

# 4. Create the Window Index using cumsum()
df2['window_idx'] = new_window_condition.cumsum()

# 5. Impute the missing dates within each window
# Example: Forward fill, then backward fill within the same window group
df2['imputed_date'] = df2.groupby(['window_idx'])['Test Date'].ffill().bfill()

print(df2.head())

   Test ID  Test Date          Tester Name Type of Question Build / Version  \
0  TL-1592 2022-06-22  Lavanya Mathialagan           Unique             0.1
1  TL-1591 2022-06-22  Lavanya Mathialagan           Unique             0.1
2  TL-2126 2023-06-23           Dhaarani S           Unique             0.1
3  TL-0823 2025-06-15  Lavanya Mathialagan              NaN             0,0
4  TL-1231 2026-02-17           Dhaarani S          Dynamic             0.1

  Sprint / Cycle Channel Tested Language Tested  \
0            NIL        Web App         English
1            NIL        Web App         English
2            NIL       WhatsApp         English
3            NIL        Web app         English
4            NIL        Web App         English

                            Question ID  \
0  1f16e1f3-24aa-61de-8005-20253ade8d6a
1  1f16e1f0-71a2-61b7-8005-82ef6f35b026
2  1f16eed6-08b5-6047-8028-401ecf8b2cef
3  1f1687ed-e881-6931-8005-c9689f44d512
4  1f16a2d6-1539-6757-8005-d10a1dc12c07

                               Query Text (Original)  ...  \
0  Is it permissible to mix NPK 19-19-19 fertiliz...  ...
1  What is the compatibility and proper applicati...  ...
2  What are the causes and effective management s...  ...
3  What are the common fungal diseases affecting ...  ...
4  Is the price of groundnut increasing or decrea...  ...

        Q-ID Consistent Across Systems? WhatsApp vs Web Answer Match?  \
0  Successfully Identified as Duplicate                           NaN
1  Successfully Identified as Duplicate                           NaN
2  Successfully Identified as Duplicate                           NaN
3  Successfully Identified as Duplicate                           Yes
4  Successfully Identified as Duplicate                           Yes

  Overall Test Status Defect Severity  \
0                Pass       No defect
1                Pass       No defect
2                Pass       NO Defect
3                Pass       No defect
4                 NaN             NaN

  Defect ID / Bug Ref\nZoho Desk Ticketing Reviewer Remarks  \
0                                      NaN              NIL
1                                      NaN              NIL
2                                      NaN              NIL
3                                      NaN              NIL
4                                      NaN              NIL

                                      Tester Remarks           Status  \
0  2 hours disclaimer is seen, Answer received af...  Expected output
1  2 Hours disclaimer is seen. Answer received af...  Expected output
2  2 hours disclaimer is seen. Received the answe...          Pending
3                                         Good to go              NaN
4                        2 hours disclaimer is seen.              NaN

  window_idx imputed_date
0          0   2022-06-22
1          0   2022-06-22
2          1   2023-06-23
3          2   2025-06-15
4          3   2026-02-17

[5 rows x 80 columns]

In [10]:
import pandas as pd

# 1. Filter for dates starting from June 8, 2026
filtered_df = df[df['Test Date'] >= '2026-06-08']

# 2. Sort by the original DataFrame index to ensure chronological log order
filtered_df = filtered_df.sort_index()

# 3. Keep the 'first' occurrence of each date based on this index order
unique_dates_df = filtered_df.drop_duplicates(subset=['Test Date'], keep='first')

# 4. Extract sequential lists ordered by their appearance in the index
sequential_dates = unique_dates_df['Test Date'].dt.strftime('%d-%m-%Y').tolist()
original_indexes = unique_dates_df.index.tolist()

# Output the paired results
i = 0
for date, idx in zip(sequential_dates, original_indexes):
    print(f"{i}.Index: {idx} -> First Occurrence of Date: {date}")
    i+=1

0.Index: 0 -> First Occurrence of Date: 08-06-2026
1.Index: 7 -> First Occurrence of Date: 09-06-2026
2.Index: 11 -> First Occurrence of Date: 09-07-2026
3.Index: 16 -> First Occurrence of Date: 09-08-2026
4.Index: 17 -> First Occurrence of Date: 09-09-2026
5.Index: 72 -> First Occurrence of Date: 10-06-2026
6.Index: 267 -> First Occurrence of Date: 11-06-2026
7.Index: 336 -> First Occurrence of Date: 11-07-2026
8.Index: 337 -> First Occurrence of Date: 11-08-2026
9.Index: 338 -> First Occurrence of Date: 11-09-2026
10.Index: 339 -> First Occurrence of Date: 11-10-2026
11.Index: 340 -> First Occurrence of Date: 11-11-2026
12.Index: 341 -> First Occurrence of Date: 11-12-2026
13.Index: 342 -> First Occurrence of Date: 13-11-2026
14.Index: 343 -> First Occurrence of Date: 14-11-2026
15.Index: 344 -> First Occurrence of Date: 15-11-2026
16.Index: 345 -> First Occurrence of Date: 16-11-2026
17.Index: 407 -> First Occurrence of Date: 12-06-2026
18.Index: 452 -> First Occurrence of Date: 14-06-2026
19.Index: 555 -> First Occurrence of Date: 13-06-2026
20.Index: 627 -> First Occurrence of Date: 14-06-2027
21.Index: 630 -> First Occurrence of Date: 14-06-2028
22.Index: 631 -> First Occurrence of Date: 14-06-2029
23.Index: 632 -> First Occurrence of Date: 14-06-2030
24.Index: 633 -> First Occurrence of Date: 14-06-2031
25.Index: 634 -> First Occurrence of Date: 14-06-2032
26.Index: 635 -> First Occurrence of Date: 14-06-2033
27.Index: 636 -> First Occurrence of Date: 14-06-2034
28.Index: 637 -> First Occurrence of Date: 14-06-2035
29.Index: 638 -> First Occurrence of Date: 14-06-2036
30.Index: 639 -> First Occurrence of Date: 14-06-2037
31.Index: 640 -> First Occurrence of Date: 14-06-2038
32.Index: 641 -> First Occurrence of Date: 14-06-2039
33.Index: 687 -> First Occurrence of Date: 15-06-2026
34.Index: 926 -> First Occurrence of Date: 16-06-2026
35.Index: 1118 -> First Occurrence of Date: 17-06-2026
36.Index: 1274 -> First Occurrence of Date: 18-06-2026
37.Index: 1407 -> First Occurrence of Date: 19-06-2026
38.Index: 1560 -> First Occurrence of Date: 20-06-2026
39.Index: 1595 -> First Occurrence of Date: 22-06-2026
40.Index: 1735 -> First Occurrence of Date: 21-06-2026
41.Index: 1992 -> First Occurrence of Date: 23-06-2026
42.Index: 2175 -> First Occurrence of Date: 24-06-2026
43.Index: 2400 -> First Occurrence of Date: 25-06-2026
44.Index: 2493 -> First Occurrence of Date: 25-06-2037
45.Index: 2494 -> First Occurrence of Date: 25-06-2038
46.Index: 2636 -> First Occurrence of Date: 26-06-2026
47.Index: 2674 -> First Occurrence of Date: 26-06-2027
48.Index: 2675 -> First Occurrence of Date: 26-06-2028
49.Index: 2676 -> First Occurrence of Date: 26-06-2029
50.Index: 2677 -> First Occurrence of Date: 26-06-2030
51.Index: 2678 -> First Occurrence of Date: 26-06-2031
52.Index: 2679 -> First Occurrence of Date: 26-06-2032
53.Index: 2680 -> First Occurrence of Date: 26-06-2033
54.Index: 2681 -> First Occurrence of Date: 26-06-2034
55.Index: 2682 -> First Occurrence of Date: 26-06-2035
56.Index: 2683 -> First Occurrence of Date: 26-06-2036
57.Index: 2684 -> First Occurrence of Date: 26-06-2037
58.Index: 2685 -> First Occurrence of Date: 26-06-2038
59.Index: 2686 -> First Occurrence of Date: 26-06-2039
60.Index: 2687 -> First Occurrence of Date: 26-06-2040
61.Index: 2688 -> First Occurrence of Date: 26-06-2041
62.Index: 2763 -> First Occurrence of Date: 27-06-2026
63.Index: 2877 -> First Occurrence of Date: 28-06-2026
64.Index: 2888 -> First Occurrence of Date: 29-06-2026
65.Index: 3155 -> First Occurrence of Date: 30-06-2026
66.Index: 3400 -> First Occurrence of Date: 01-07-2026
67.Index: 3401 -> First Occurrence of Date: 01-08-2026
68.Index: 3402 -> First Occurrence of Date: 01-09-2026
69.Index: 3600 -> First Occurrence of Date: 02-07-2026
70.Index: 3780 -> First Occurrence of Date: 03-07-2026
71.Index: 3991 -> First Occurrence of Date: 04-07-2026
72.Index: 4136 -> First Occurrence of Date: 05-07-2026
73.Index: 4223 -> First Occurrence of Date: 06-07-2026
74.Index: 4392 -> First Occurrence of Date: 07-07-2026
75.Index: 4627 -> First Occurrence of Date: 08-07-2026
76.Index: 5046 -> First Occurrence of Date: 10-07-2026
77.Index: 5395 -> First Occurrence of Date: 12-07-2026
78.Index: 5481 -> First Occurrence of Date: 13-07-2026

In [11]:
import pandas as pd

df5 = df

# # 1. Convert column to datetime (if not already done)
# df5['date'] = pd.to_datetime(df5['date'], dayfirst=True, errors='coerce')

# 2. Ensure data is sorted by its original index order before fixing
df5 = df5.sort_index()

# 3. Define the rules for a "Wrong" date based on your log patterns:
# - Rule A: The year skips into the future (e.g., greater than 2026)
# - Rule B: The date jumps ahead of our current real-world timeline
#           (Since today is in July 2026, logs from 2027+ or late 2026 are impossible)
current_year = 2026
is_wrong_year = df5['Test Date'].dt.year > current_year

# 4. Wipe out the incorrect dates by setting them to NaT (Not a Time)
df5.loc[is_wrong_year, 'Test Date'] = pd.NaT

# 5. Apply Strategy: Use the previous correct date to impute them
df5['Test Date'] = df5['Test Date'].ffill()

# (Optional) If any wrong dates appeared at the very first row,
# backfill just in case to avoid leaving a NaT at index 0
df5['Test Date'] = df5['Test Date'].bfill()

In [12]:
df5['Test Date'].unique()

<DatetimeArray>
['2026-06-08 00:00:00', '2026-06-09 00:00:00', '2026-07-09 00:00:00',
 '2026-08-09 00:00:00', '2026-09-09 00:00:00', '2026-06-10 00:00:00',
 '2026-06-11 00:00:00', '2026-07-11 00:00:00', '2026-08-11 00:00:00',
 '2026-09-11 00:00:00', '2026-10-11 00:00:00', '2026-11-11 00:00:00',
 '2026-12-11 00:00:00', '2026-11-13 00:00:00', '2026-11-14 00:00:00',
 '2026-11-15 00:00:00', '2026-11-16 00:00:00', '2026-06-12 00:00:00',
 '2026-06-14 00:00:00', '2026-06-13 00:00:00', '2026-06-15 00:00:00',
 '2025-06-15 00:00:00', '2026-06-16 00:00:00', '2026-06-17 00:00:00',
 '2026-02-17 00:00:00', '2026-06-18 00:00:00', '2026-06-19 00:00:00',
 '2026-06-20 00:00:00', '2022-06-22 00:00:00', '2026-06-22 00:00:00',
 '2026-06-21 00:00:00', '2026-06-23 00:00:00', '2023-06-23 00:00:00',
 '2026-06-24 00:00:00', '2026-06-25 00:00:00', '2026-06-26 00:00:00',
 '2026-06-27 00:00:00', '2026-06-28 00:00:00', '2026-06-29 00:00:00',
 '2026-06-30 00:00:00', '2026-06-01 00:00:00', '2026-07-01 00:00:00',
 '2026-08-01 00:00:00', '2026-09-01 00:00:00', '2026-07-02 00:00:00',
 '2026-07-03 00:00:00', '2026-07-04 00:00:00', '2026-06-04 00:00:00',
 '2026-07-05 00:00:00', '2026-07-06 00:00:00', '2026-07-07 00:00:00',
 '2026-07-08 00:00:00', '2026-07-10 00:00:00', '2026-07-12 00:00:00',
 '2026-07-13 00:00:00']
Length: 55, dtype: datetime64[ns]

In [13]:
df5.to_csv("Checkpoint1.csv", index = False)

In [14]:
import pandas as pd

df6 = df

# 1. Convert column to datetime
df6['Test Date'] = pd.to_datetime(df6['Test Date'], dayfirst=True, errors='coerce')

# 2. Ensure data is sorted by its original index order
df6 = df6.sort_index()

# 3. Define the threshold as today's actual date (July 14, 2026)
current_date = pd.to_datetime('2026-07-14')

# 4. Flag both future years (e.g., 2027+) and future months (e.g., August 2026)
is_impossible_future_date = df6['Test Date'] > current_date

# 5. Clear out the bad data rows
df6.loc[is_impossible_future_date, 'Test Date'] = pd.NaT

# 6. Apply your strategy: Forward fill from the last known good date
df6['Test Date'] = df6['Test Date'].ffill()

# Backfill as a safety net if the very first row happens to be broken
df6['Test Date'] = df6['Test Date'].bfill()

In [17]:
df6 = df6.sort_values(by='Test Date').reset_index(drop=True)

In [18]:
print(df6.head())
print(df6['Test Date'].unique())

   Test ID  Test Date          Tester Name Type of Question Build / Version  \
0  TL-1592 2022-06-22  Lavanya Mathialagan           Unique             0.1
1  TL-1591 2022-06-22  Lavanya Mathialagan           Unique             0.1
2  TL-2126 2023-06-23           Dhaarani S           Unique             0.1
3  TL-0823 2025-06-15  Lavanya Mathialagan              NaN             0,0
4  TL-1230 2026-02-17           Dhaarani S          Dynamic             0.1

  Sprint / Cycle Channel Tested Language Tested  \
0            NIL        Web App         English
1            NIL        Web App         English
2            NIL       WhatsApp         English
3            NIL        Web app         English
4            NIL       WhatsApp         English

                            Question ID  \
0  1f16e1f3-24aa-61de-8005-20253ade8d6a
1  1f16e1f0-71a2-61b7-8005-82ef6f35b026
2  1f16eed6-08b5-6047-8028-401ecf8b2cef
3  1f1687ed-e881-6931-8005-c9689f44d512
4  1f16a2e1-154e-6238-8054-8dd4efd34c07

                               Query Text (Original)  ...  \
0  Is it permissible to mix NPK 19-19-19 fertiliz...  ...
1  What is the compatibility and proper applicati...  ...
2  What are the causes and effective management s...  ...
3  What are the common fungal diseases affecting ...  ...
4  Based on current weather, what advisory do you...  ...

  Question Saved in DB? Answer Saved in DB?  \
0                 Saved               Saved
1                 Saved               Saved
2                 Saved               Saved
3                 Saved               Saved
4                 Saved                 NaN

        Q-ID Consistent Across Systems? WhatsApp vs Web Answer Match?  \
0  Successfully Identified as Duplicate                           NaN
1  Successfully Identified as Duplicate                           NaN
2  Successfully Identified as Duplicate                           NaN
3  Successfully Identified as Duplicate                           Yes
4  Successfully Identified as Duplicate                            No

  Overall Test Status Defect Severity  \
0                Pass       No defect
1                Pass       No defect
2                Pass       NO Defect
3                Pass       No defect
4                 NaN             NaN

  Defect ID / Bug Ref\nZoho Desk Ticketing Reviewer Remarks  \
0                                      NaN              NIL
1                                      NaN              NIL
2                                      NaN              NIL
3                                      NaN              NIL
4                                      NaN              NIL

                                      Tester Remarks           Status
0  2 hours disclaimer is seen, Answer received af...  Expected output
1  2 Hours disclaimer is seen. Answer received af...  Expected output
2  2 hours disclaimer is seen. Received the answe...          Pending
3                                         Good to go              NaN
4                        2 hours disclaimer is seen.              NaN

[5 rows x 78 columns]
<DatetimeArray>
['2022-06-22 00:00:00', '2023-06-23 00:00:00', '2025-06-15 00:00:00',
 '2026-02-17 00:00:00', '2026-06-01 00:00:00', '2026-06-04 00:00:00',
 '2026-06-08 00:00:00', '2026-06-09 00:00:00', '2026-06-10 00:00:00',
 '2026-06-11 00:00:00', '2026-06-12 00:00:00', '2026-06-13 00:00:00',
 '2026-06-14 00:00:00', '2026-06-15 00:00:00', '2026-06-16 00:00:00',
 '2026-06-17 00:00:00', '2026-06-18 00:00:00', '2026-06-19 00:00:00',
 '2026-06-20 00:00:00', '2026-06-21 00:00:00', '2026-06-22 00:00:00',
 '2026-06-23 00:00:00', '2026-06-24 00:00:00', '2026-06-25 00:00:00',
 '2026-06-26 00:00:00', '2026-06-27 00:00:00', '2026-06-28 00:00:00',
 '2026-06-29 00:00:00', '2026-06-30 00:00:00', '2026-07-01 00:00:00',
 '2026-07-02 00:00:00', '2026-07-03 00:00:00', '2026-07-04 00:00:00',
 '2026-07-05 00:00:00', '2026-07-06 00:00:00', '2026-07-07 00:00:00',
 '2026-07-08 00:00:00', '2026-07-09 00:00:00', '2026-07-10 00:00:00',
 '2026-07-11 00:00:00', '2026-07-12 00:00:00', '2026-07-13 00:00:00']
Length: 42, dtype: datetime64[ns]

In [15]:
# Removing final unknown Tester Name Row

df6.dropna(subset=['Tester Name'], inplace=True)

df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5258 entries, 0 to 5523
Data columns (total 78 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5258 non-null   object
 1   Test Date                                5258 non-null   datetime64[ns]
 2   Tester Name                              5258 non-null   object
 3   Type of Question                         4046 non-null   object
 4   Build / Version                          5249 non-null   object
 5   Sprint / Cycle                           5197 non-null   object
 6   Channel Tested                           5211 non-null   object
 7   Language Tested                          5240 non-null   object
 8   Question ID                              5011 non-null   object
 9   Query Text (Original)                    5258 non-null   object
 10  Question Category                        5094 non-null   object
 11  Time Question Asked (HH:MM:SS)           5081 non-null   object
 12  Time Answer Received (HH:MM:SS)          4113 non-null   object
 13  Response Time (mins) [Auto]              3723 non-null   object
 14  SLA Status                               4347 non-null   object
 15  Question in Review Model?                4418 non-null   object
 16  Question Correctly Framed?               4550 non-null   object
 17  Original Language                        4662 non-null   object
 18  Translated Language                      4363 non-null   object
 19  Translation Quality                      3757 non-null   object
 20  Translation Error Type                   3320 non-null   object
 21  Tagging                                  2586 non-null   object
 22  Allocated to Reviewer?                   2508 non-null   object
 23  Author's Name                            3058 non-null   object
 24  Author Assignment Time                   892 non-null    object
 25  Author Completion Time                   843 non-null    object
 26  Author TAT (mins) [Auto]                 799 non-null    object
 27  Reviewer1 Name                           1081 non-null   object
 28  Reviewer1 Assignment Time                880 non-null    object
 29  Reviewer1 Completion Time                836 non-null    object
 30  Review1 TAT (mins) [Auto]                794 non-null    object
 31  Reviewer2 Name                           1081 non-null   object
 32  Reviewer2 Assignment Time                880 non-null    object
 33  Reviewer2 Completion Time                836 non-null    object
 34  Review2 TAT (mins) [Auto]                794 non-null    object
 35  Reviewer3 Name                           1058 non-null   object
 36  Reviewer3 Assignment Time                880 non-null    object
 37  Reviewer3 Completion Time                833 non-null    object
 38  Review3 TAT (mins) [Auto]                792 non-null    object
 39  Reviewer4 Name                           26 non-null     object
 40  Reviewer4 Assignment Time                24 non-null     object
 41  Reviewer4 Completion Time                22 non-null     object
 42  Review4 TAT (mins) [Auto]                21 non-null     object
 43  Reviewer5 Name                           13 non-null     object
 44  Reviewer5 Assignment Time                12 non-null     object
 45  Reviewer5 Completion Time                12 non-null     object
 46  Review5 TAT (mins) [Auto]                12 non-null     object
 47  Moderator's Name                         920 non-null    object
 48  Moderator Assignment Time                444 non-null    object
 49  ModeratorCompletion Time                 871 non-null    object
 50  Moderator TAT (mins) [Auto]              825 non-null    object
 51  Follow-up Q in Review Model?             2088 non-null   object
 52  Answer Scientifically Correct?           3945 non-null   object
 53  Expert Name Displayed?                   3774 non-null   object
 54  Correct Expert Name?                     3736 non-null   object
 55  Source Links Provided?                   3772 non-null   object
 56  120-min Msg Shown to User?               2314 non-null   object
 57  Notification Received?                   2156 non-null   object
 58  Notification on Same Thread?             1390 non-null   object
 59  Notification Linked Correct Q-ID?        929 non-null    object
 60  Voice Input Working?                     2862 non-null   object
 61  Voice Output Working?                    2848 non-null   object
 62  Voice Input Quality                      2886 non-null   object
 63  Voice Output Quality                     2847 non-null   object
 64  Voice Issue Description                  2068 non-null   object
 65  Weather Q Answered Correctly?            176 non-null    object
 66  Mandi Price Q Correct?                   163 non-null    object
 67  Scheme Q Correct?                        66 non-null     object
 68  Question Saved in DB?                    3837 non-null   object
 69  Answer Saved in DB?                      3526 non-null   object
 70  Q-ID Consistent Across Systems?          3426 non-null   object
 71  WhatsApp vs Web Answer Match?            1674 non-null   object
 72  Overall Test Status                      3745 non-null   object
 73  Defect Severity                          3194 non-null   object
 74  Defect ID / Bug Ref
Zoho Desk Ticketing  1704 non-null   object
 75  Reviewer Remarks                         4076 non-null   object
 76  Tester Remarks                           4247 non-null   object
 77  Status                                   3603 non-null   object
dtypes: datetime64[ns](1), object(77)
memory usage: 3.2+ MB

In [20]:
import pandas as pd

# Re-initialize df6 from the base df to ensure 'Test Date' is datetime
df6 = df.copy()

# Ensure 'Test Date' is datetime (re-applying logic from cell 74c8b6e0)
df6['Test Date'] = pd.to_datetime(df6['Test Date'], dayfirst=True, errors='coerce')

# Re-apply the logic to handle impossible future dates from cell 74c8b6e0
current_date = pd.to_datetime('2026-07-14')
is_impossible_future_date = df6['Test Date'] > current_date
df6.loc[is_impossible_future_date, 'Test Date'] = pd.NaT
df6['Test Date'] = df6['Test Date'].ffill()
df6['Test Date'] = df6['Test Date'].bfill()

# Re-apply sorting from cell 762556bd
df6 = df6.sort_values(by='Test Date').reset_index(drop=True)

# Re-apply dropna from cell f1c36132-5f23-49f2-9fa7-bdb8ee525ba7
df6.dropna(subset=['Tester Name'], inplace=True)

# Now, apply the requested year change: change all years to 2026
df6['Test Date'] = df6['Test Date'].apply(lambda x: x.replace(year=2026) if pd.notnull(x) else x)

print(df6['Test Date'].unique())

<DatetimeArray>
['2026-06-22 00:00:00', '2026-06-23 00:00:00', '2026-06-15 00:00:00',
 '2026-02-17 00:00:00', '2026-06-01 00:00:00', '2026-06-04 00:00:00',
 '2026-06-08 00:00:00', '2026-06-09 00:00:00', '2026-06-10 00:00:00',
 '2026-06-11 00:00:00', '2026-06-12 00:00:00', '2026-06-13 00:00:00',
 '2026-06-14 00:00:00', '2026-06-16 00:00:00', '2026-06-17 00:00:00',
 '2026-06-18 00:00:00', '2026-06-19 00:00:00', '2026-06-20 00:00:00',
 '2026-06-21 00:00:00', '2026-06-24 00:00:00', '2026-06-25 00:00:00',
 '2026-06-26 00:00:00', '2026-06-27 00:00:00', '2026-06-28 00:00:00',
 '2026-06-29 00:00:00', '2026-06-30 00:00:00', '2026-07-01 00:00:00',
 '2026-07-02 00:00:00', '2026-07-03 00:00:00', '2026-07-04 00:00:00',
 '2026-07-05 00:00:00', '2026-07-06 00:00:00', '2026-07-07 00:00:00',
 '2026-07-08 00:00:00', '2026-07-09 00:00:00', '2026-07-10 00:00:00',
 '2026-07-11 00:00:00', '2026-07-12 00:00:00', '2026-07-13 00:00:00']
Length: 39, dtype: datetime64[ns]

In [21]:
df6 = df6.sort_values(by='Test Date').reset_index(drop=True)
print(df6.head())
print(df6['Test Date'].unique())

   Test ID  Test Date          Tester Name Type of Question Build / Version  \
0  TL-1230 2026-02-17           Dhaarani S          Dynamic             0.1
1  TL-1231 2026-02-17           Dhaarani S          Dynamic             0.1
2  TL-3400 2026-06-01  Lavanya Mathialagan           Unique             0.1
3  TL-3403 2026-06-01  Lavanya Mathialagan           Unique             0.1
4  TL-3404 2026-06-01  Lavanya Mathialagan           Unique             0.1

  Sprint / Cycle Channel Tested Language Tested  \
0            NIL       WhatsApp         English
1            NIL        Web App         English
2            NIL        Web App         English
3            NIL        Web App         English
4            NIL        Web App         English

                            Question ID  \
0  1f16a2e1-154e-6238-8054-8dd4efd34c07
1  1f16a2d6-1539-6757-8005-d10a1dc12c07
2  1f174f07-5dee-6b09-8005-20186a862f1a
3  1f174f38-65c5-63a1-8005-a0b1eb75bc19
4  1f174f3d-14f4-66de-8005-d80bf76968be

                               Query Text (Original)  ...  \
0  Based on current weather, what advisory do you...  ...
1  Is the price of groundnut increasing or decrea...  ...
2  How can I identify and manage Brown Spot disea...  ...
3  What are the recommended methods and chemicals...  ...
4  How can I identify and control the swarming ca...  ...

  Question Saved in DB? Answer Saved in DB?  \
0                 Saved                 NaN
1                   NaN                 NaN
2                 Saved               Saved
3                 Saved               Saved
4                 Saved               Saved

        Q-ID Consistent Across Systems? WhatsApp vs Web Answer Match?  \
0  Successfully Identified as Duplicate                            No
1  Successfully Identified as Duplicate                           Yes
2                                   NaN                           NaN
3                                   NaN                           NaN
4                                   NaN                           NaN

  Overall Test Status Defect Severity  \
0                 NaN             NaN
1                 NaN             NaN
2                PASS       NO DEFECT
3                PASS       NO DEFECT
4                PASS       NO DEFECT

  Defect ID / Bug Ref\nZoho Desk Ticketing Reviewer Remarks  \
0                                      NaN              NIL
1                                      NaN              NIL
2                                      NIL              NIL
3                                      NIL              NIL
4                                      NIL              NIL

                                      Tester Remarks           Status
0                        2 hours disclaimer is seen.              NaN
1                        2 hours disclaimer is seen.              NaN
2  2 hours disclaimer is given. Regenerated after...  Expected Output
3  2 hours disclaimer is given. Regenerated after...  Expected Output
4  2 hours disclaimer is given. Regenerated after...  Expected Output

[5 rows x 78 columns]
<DatetimeArray>
['2026-02-17 00:00:00', '2026-06-01 00:00:00', '2026-06-04 00:00:00',
 '2026-06-08 00:00:00', '2026-06-09 00:00:00', '2026-06-10 00:00:00',
 '2026-06-11 00:00:00', '2026-06-12 00:00:00', '2026-06-13 00:00:00',
 '2026-06-14 00:00:00', '2026-06-15 00:00:00', '2026-06-16 00:00:00',
 '2026-06-17 00:00:00', '2026-06-18 00:00:00', '2026-06-19 00:00:00',
 '2026-06-20 00:00:00', '2026-06-21 00:00:00', '2026-06-22 00:00:00',
 '2026-06-23 00:00:00', '2026-06-24 00:00:00', '2026-06-25 00:00:00',
 '2026-06-26 00:00:00', '2026-06-27 00:00:00', '2026-06-28 00:00:00',
 '2026-06-29 00:00:00', '2026-06-30 00:00:00', '2026-07-01 00:00:00',
 '2026-07-02 00:00:00', '2026-07-03 00:00:00', '2026-07-04 00:00:00',
 '2026-07-05 00:00:00', '2026-07-06 00:00:00', '2026-07-07 00:00:00',
 '2026-07-08 00:00:00', '2026-07-09 00:00:00', '2026-07-10 00:00:00',
 '2026-07-11 00:00:00', '2026-07-12 00:00:00', '2026-07-13 00:00:00']
Length: 39, dtype: datetime64[ns]

In [22]:
start_date = pd.to_datetime('2026-06-08')
end_date = pd.to_datetime('2026-07-13')
df6 = df6[(df6['Test Date'] >= start_date) & (df6['Test Date'] <= end_date)].reset_index(drop=True)

print(df6.head())
print(df6['Test Date'].unique())

   Test ID  Test Date          Tester Name Type of Question Build / Version  \
0        1 2026-06-08           Souvik Roy              NaN             0.1
1  TL-0007 2026-06-08     T.Vishnu Vardhan              NaN             0.1
2        2 2026-06-08              Nimisha              NaN             0.1
3  TL-0065 2026-06-09  Lavanya Mathialagan              NaN             0.1
4  TL-0009 2026-06-09              JOYDEEP              NaN             0.1

  Sprint / Cycle Channel Tested Language Tested  \
0            NIL        Web App         English
1            NIL        Web App         English
2            NIL        Web App         English
3            NIL        Web App         English
4            NIL           BOTH         English

                              Question ID  \
0    1f16318c-9102-683c-8005-3bbd319b092f
1  1f1646aa-6b75-6c40-80a6-c4c0a58e552f\n
2    1f163288-99fc-62cf-8005-31d3e7adec03
3  1f164095-e3d5-6ce8-800\n5-ed467201e41e
4    1f163c33-2eb6-624d-8005-e22d3237d7f8

                               Query Text (Original)  ...  \
0                      How to control Dila in Paddy?  ...
1  Which varieties of chilli are most suitable fo...  ...
2  What are the primary causes of stunted growth ...  ...
3  \r\nHow can fish amino acids be prepared and u...  ...
4  What is the correct method and procedure for p...  ...

  Question Saved in DB? Answer Saved in DB?  \
0             Duplicate           Duplicate
1                   NaN                 NaN
2             Duplicate           Duplicate
3                   NaN                 NaN
4                 Saved               Saved

        Q-ID Consistent Across Systems? WhatsApp vs Web Answer Match?  \
0  Successfully Identified as Duplicate                           NaN
1  Successfully Identified as Duplicate                           NaN
2  Successfully Identified as Duplicate                           NaN
3  Successfully Identified as Duplicate                           NaN
4  Successfully Identified as Duplicate                           Yes

  Overall Test Status Defect Severity  \
0                Pass             Low
1                 NaN             NaN
2                Pass       NO Defect
3                 NaN             NaN
4                Pass             NaN

            Defect ID / Bug Ref\nZoho Desk Ticketing Reviewer Remarks  \
0  https://desk.zoho.in/agent/annamai/annam-ai/ti...              NIL
1                                                NaN              NIL
2                                                NaN              NIL
3                                                NaN              NIL
4                                                NaN              NIL

                                      Tester Remarks Status
0  District names appeared as "ALL", it should ha...    NaN
1                         2 hours disclaimer is seen    NaN
2      for longer text, audio output takes more time    NaN
3  2 Hours disclaimer is seen. Even after 2 hours...    NaN
4  District names appeared as "ALL", it should ha...    NaN

[5 rows x 78 columns]
<DatetimeArray>
['2026-06-08 00:00:00', '2026-06-09 00:00:00', '2026-06-10 00:00:00',
 '2026-06-11 00:00:00', '2026-06-12 00:00:00', '2026-06-13 00:00:00',
 '2026-06-14 00:00:00', '2026-06-15 00:00:00', '2026-06-16 00:00:00',
 '2026-06-17 00:00:00', '2026-06-18 00:00:00', '2026-06-19 00:00:00',
 '2026-06-20 00:00:00', '2026-06-21 00:00:00', '2026-06-22 00:00:00',
 '2026-06-23 00:00:00', '2026-06-24 00:00:00', '2026-06-25 00:00:00',
 '2026-06-26 00:00:00', '2026-06-27 00:00:00', '2026-06-28 00:00:00',
 '2026-06-29 00:00:00', '2026-06-30 00:00:00', '2026-07-01 00:00:00',
 '2026-07-02 00:00:00', '2026-07-03 00:00:00', '2026-07-04 00:00:00',
 '2026-07-05 00:00:00', '2026-07-06 00:00:00', '2026-07-07 00:00:00',
 '2026-07-08 00:00:00', '2026-07-09 00:00:00', '2026-07-10 00:00:00',
 '2026-07-11 00:00:00', '2026-07-12 00:00:00', '2026-07-13 00:00:00']
Length: 36, dtype: datetime64[ns]

In [23]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 78 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Type of Question                         3899 non-null   object
 4   Build / Version                          5102 non-null   object
 5   Sprint / Cycle                           5050 non-null   object
 6   Channel Tested                           5064 non-null   object
 7   Language Tested                          5093 non-null   object
 8   Question ID                              4864 non-null   object
 9   Query Text (Original)                    5111 non-null   object
 10  Question Category                        4947 non-null   object
 11  Time Question Asked (HH:MM:SS)           4934 non-null   object
 12  Time Answer Received (HH:MM:SS)          3976 non-null   object
 13  Response Time (mins) [Auto]              3612 non-null   object
 14  SLA Status                               4207 non-null   object
 15  Question in Review Model?                4272 non-null   object
 16  Question Correctly Framed?               4404 non-null   object
 17  Original Language                        4516 non-null   object
 18  Translated Language                      4217 non-null   object
 19  Translation Quality                      3611 non-null   object
 20  Translation Error Type                   3177 non-null   object
 21  Tagging                                  2499 non-null   object
 22  Allocated to Reviewer?                   2419 non-null   object
 23  Author's Name                            2948 non-null   object
 24  Author Assignment Time                   833 non-null    object
 25  Author Completion Time                   784 non-null    object
 26  Author TAT (mins) [Auto]                 740 non-null    object
 27  Reviewer1 Name                           1023 non-null   object
 28  Reviewer1 Assignment Time                822 non-null    object
 29  Reviewer1 Completion Time                778 non-null    object
 30  Review1 TAT (mins) [Auto]                736 non-null    object
 31  Reviewer2 Name                           1023 non-null   object
 32  Reviewer2 Assignment Time                822 non-null    object
 33  Reviewer2 Completion Time                778 non-null    object
 34  Review2 TAT (mins) [Auto]                736 non-null    object
 35  Reviewer3 Name                           1000 non-null   object
 36  Reviewer3 Assignment Time                822 non-null    object
 37  Reviewer3 Completion Time                775 non-null    object
 38  Review3 TAT (mins) [Auto]                734 non-null    object
 39  Reviewer4 Name                           21 non-null     object
 40  Reviewer4 Assignment Time                19 non-null     object
 41  Reviewer4 Completion Time                17 non-null     object
 42  Review4 TAT (mins) [Auto]                16 non-null     object
 43  Reviewer5 Name                           8 non-null      object
 44  Reviewer5 Assignment Time                7 non-null      object
 45  Reviewer5 Completion Time                7 non-null      object
 46  Review5 TAT (mins) [Auto]                7 non-null      object
 47  Moderator's Name                         864 non-null    object
 48  Moderator Assignment Time                397 non-null    object
 49  ModeratorCompletion Time                 817 non-null    object
 50  Moderator TAT (mins) [Auto]              772 non-null    object
 51  Follow-up Q in Review Model?             2048 non-null   object
 52  Answer Scientifically Correct?           3807 non-null   object
 53  Expert Name Displayed?                   3637 non-null   object
 54  Correct Expert Name?                     3598 non-null   object
 55  Source Links Provided?                   3637 non-null   object
 56  120-min Msg Shown to User?               2254 non-null   object
 57  Notification Received?                   2093 non-null   object
 58  Notification on Same Thread?             1343 non-null   object
 59  Notification Linked Correct Q-ID?        895 non-null    object
 60  Voice Input Working?                     2777 non-null   object
 61  Voice Output Working?                    2753 non-null   object
 62  Voice Input Quality                      2791 non-null   object
 63  Voice Output Quality                     2752 non-null   object
 64  Voice Issue Description                  1998 non-null   object
 65  Weather Q Answered Correctly?            175 non-null    object
 66  Mandi Price Q Correct?                   161 non-null    object
 67  Scheme Q Correct?                        66 non-null     object
 68  Question Saved in DB?                    3694 non-null   object
 69  Answer Saved in DB?                      3394 non-null   object
 70  Q-ID Consistent Across Systems?          3375 non-null   object
 71  WhatsApp vs Web Answer Match?            1672 non-null   object
 72  Overall Test Status                      3608 non-null   object
 73  Defect Severity                          3060 non-null   object
 74  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 75  Reviewer Remarks                         3941 non-null   object
 76  Tester Remarks                           4113 non-null   object
 77  Status                                   3459 non-null   object
dtypes: datetime64[ns](1), object(77)
memory usage: 3.0+ MB

In [24]:
df6.drop(columns=['Type of Question'], inplace=True)
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 77 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5102 non-null   object
 4   Sprint / Cycle                           5050 non-null   object
 5   Channel Tested                           5064 non-null   object
 6   Language Tested                          5093 non-null   object
 7   Question ID                              4864 non-null   object
 8   Query Text (Original)                    5111 non-null   object
 9   Question Category                        4947 non-null   object
 10  Time Question Asked (HH:MM:SS)           4934 non-null   object
 11  Time Answer Received (HH:MM:SS)          3976 non-null   object
 12  Response Time (mins) [Auto]              3612 non-null   object
 13  SLA Status                               4207 non-null   object
 14  Question in Review Model?                4272 non-null   object
 15  Question Correctly Framed?               4404 non-null   object
 16  Original Language                        4516 non-null   object
 17  Translated Language                      4217 non-null   object
 18  Translation Quality                      3611 non-null   object
 19  Translation Error Type                   3177 non-null   object
 20  Tagging                                  2499 non-null   object
 21  Allocated to Reviewer?                   2419 non-null   object
 22  Author's Name                            2948 non-null   object
 23  Author Assignment Time                   833 non-null    object
 24  Author Completion Time                   784 non-null    object
 25  Author TAT (mins) [Auto]                 740 non-null    object
 26  Reviewer1 Name                           1023 non-null   object
 27  Reviewer1 Assignment Time                822 non-null    object
 28  Reviewer1 Completion Time                778 non-null    object
 29  Review1 TAT (mins) [Auto]                736 non-null    object
 30  Reviewer2 Name                           1023 non-null   object
 31  Reviewer2 Assignment Time                822 non-null    object
 32  Reviewer2 Completion Time                778 non-null    object
 33  Review2 TAT (mins) [Auto]                736 non-null    object
 34  Reviewer3 Name                           1000 non-null   object
 35  Reviewer3 Assignment Time                822 non-null    object
 36  Reviewer3 Completion Time                775 non-null    object
 37  Review3 TAT (mins) [Auto]                734 non-null    object
 38  Reviewer4 Name                           21 non-null     object
 39  Reviewer4 Assignment Time                19 non-null     object
 40  Reviewer4 Completion Time                17 non-null     object
 41  Review4 TAT (mins) [Auto]                16 non-null     object
 42  Reviewer5 Name                           8 non-null      object
 43  Reviewer5 Assignment Time                7 non-null      object
 44  Reviewer5 Completion Time                7 non-null      object
 45  Review5 TAT (mins) [Auto]                7 non-null      object
 46  Moderator's Name                         864 non-null    object
 47  Moderator Assignment Time                397 non-null    object
 48  ModeratorCompletion Time                 817 non-null    object
 49  Moderator TAT (mins) [Auto]              772 non-null    object
 50  Follow-up Q in Review Model?             2048 non-null   object
 51  Answer Scientifically Correct?           3807 non-null   object
 52  Expert Name Displayed?                   3637 non-null   object
 53  Correct Expert Name?                     3598 non-null   object
 54  Source Links Provided?                   3637 non-null   object
 55  120-min Msg Shown to User?               2254 non-null   object
 56  Notification Received?                   2093 non-null   object
 57  Notification on Same Thread?             1343 non-null   object
 58  Notification Linked Correct Q-ID?        895 non-null    object
 59  Voice Input Working?                     2777 non-null   object
 60  Voice Output Working?                    2753 non-null   object
 61  Voice Input Quality                      2791 non-null   object
 62  Voice Output Quality                     2752 non-null   object
 63  Voice Issue Description                  1998 non-null   object
 64  Weather Q Answered Correctly?            175 non-null    object
 65  Mandi Price Q Correct?                   161 non-null    object
 66  Scheme Q Correct?                        66 non-null     object
 67  Question Saved in DB?                    3694 non-null   object
 68  Answer Saved in DB?                      3394 non-null   object
 69  Q-ID Consistent Across Systems?          3375 non-null   object
 70  WhatsApp vs Web Answer Match?            1672 non-null   object
 71  Overall Test Status                      3608 non-null   object
 72  Defect Severity                          3060 non-null   object
 73  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 74  Reviewer Remarks                         3941 non-null   object
 75  Tester Remarks                           4113 non-null   object
 76  Status                                   3459 non-null   object
dtypes: datetime64[ns](1), object(76)
memory usage: 3.0+ MB

In [25]:
df6.drop(columns=['Sprint / Cycle'], inplace=True)
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 76 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5102 non-null   object
 4   Channel Tested                           5064 non-null   object
 5   Language Tested                          5093 non-null   object
 6   Question ID                              4864 non-null   object
 7   Query Text (Original)                    5111 non-null   object
 8   Question Category                        4947 non-null   object
 9   Time Question Asked (HH:MM:SS)           4934 non-null   object
 10  Time Answer Received (HH:MM:SS)          3976 non-null   object
 11  Response Time (mins) [Auto]              3612 non-null   object
 12  SLA Status                               4207 non-null   object
 13  Question in Review Model?                4272 non-null   object
 14  Question Correctly Framed?               4404 non-null   object
 15  Original Language                        4516 non-null   object
 16  Translated Language                      4217 non-null   object
 17  Translation Quality                      3611 non-null   object
 18  Translation Error Type                   3177 non-null   object
 19  Tagging                                  2499 non-null   object
 20  Allocated to Reviewer?                   2419 non-null   object
 21  Author's Name                            2948 non-null   object
 22  Author Assignment Time                   833 non-null    object
 23  Author Completion Time                   784 non-null    object
 24  Author TAT (mins) [Auto]                 740 non-null    object
 25  Reviewer1 Name                           1023 non-null   object
 26  Reviewer1 Assignment Time                822 non-null    object
 27  Reviewer1 Completion Time                778 non-null    object
 28  Review1 TAT (mins) [Auto]                736 non-null    object
 29  Reviewer2 Name                           1023 non-null   object
 30  Reviewer2 Assignment Time                822 non-null    object
 31  Reviewer2 Completion Time                778 non-null    object
 32  Review2 TAT (mins) [Auto]                736 non-null    object
 33  Reviewer3 Name                           1000 non-null   object
 34  Reviewer3 Assignment Time                822 non-null    object
 35  Reviewer3 Completion Time                775 non-null    object
 36  Review3 TAT (mins) [Auto]                734 non-null    object
 37  Reviewer4 Name                           21 non-null     object
 38  Reviewer4 Assignment Time                19 non-null     object
 39  Reviewer4 Completion Time                17 non-null     object
 40  Review4 TAT (mins) [Auto]                16 non-null     object
 41  Reviewer5 Name                           8 non-null      object
 42  Reviewer5 Assignment Time                7 non-null      object
 43  Reviewer5 Completion Time                7 non-null      object
 44  Review5 TAT (mins) [Auto]                7 non-null      object
 45  Moderator's Name                         864 non-null    object
 46  Moderator Assignment Time                397 non-null    object
 47  ModeratorCompletion Time                 817 non-null    object
 48  Moderator TAT (mins) [Auto]              772 non-null    object
 49  Follow-up Q in Review Model?             2048 non-null   object
 50  Answer Scientifically Correct?           3807 non-null   object
 51  Expert Name Displayed?                   3637 non-null   object
 52  Correct Expert Name?                     3598 non-null   object
 53  Source Links Provided?                   3637 non-null   object
 54  120-min Msg Shown to User?               2254 non-null   object
 55  Notification Received?                   2093 non-null   object
 56  Notification on Same Thread?             1343 non-null   object
 57  Notification Linked Correct Q-ID?        895 non-null    object
 58  Voice Input Working?                     2777 non-null   object
 59  Voice Output Working?                    2753 non-null   object
 60  Voice Input Quality                      2791 non-null   object
 61  Voice Output Quality                     2752 non-null   object
 62  Voice Issue Description                  1998 non-null   object
 63  Weather Q Answered Correctly?            175 non-null    object
 64  Mandi Price Q Correct?                   161 non-null    object
 65  Scheme Q Correct?                        66 non-null     object
 66  Question Saved in DB?                    3694 non-null   object
 67  Answer Saved in DB?                      3394 non-null   object
 68  Q-ID Consistent Across Systems?          3375 non-null   object
 69  WhatsApp vs Web Answer Match?            1672 non-null   object
 70  Overall Test Status                      3608 non-null   object
 71  Defect Severity                          3060 non-null   object
 72  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 73  Reviewer Remarks                         3941 non-null   object
 74  Tester Remarks                           4113 non-null   object
 75  Status                                   3459 non-null   object
dtypes: datetime64[ns](1), object(75)
memory usage: 3.0+ MB

In [26]:
df6['Build / Version'] = '0.1'
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 76 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5111 non-null   object
 4   Channel Tested                           5064 non-null   object
 5   Language Tested                          5093 non-null   object
 6   Question ID                              4864 non-null   object
 7   Query Text (Original)                    5111 non-null   object
 8   Question Category                        4947 non-null   object
 9   Time Question Asked (HH:MM:SS)           4934 non-null   object
 10  Time Answer Received (HH:MM:SS)          3976 non-null   object
 11  Response Time (mins) [Auto]              3612 non-null   object
 12  SLA Status                               4207 non-null   object
 13  Question in Review Model?                4272 non-null   object
 14  Question Correctly Framed?               4404 non-null   object
 15  Original Language                        4516 non-null   object
 16  Translated Language                      4217 non-null   object
 17  Translation Quality                      3611 non-null   object
 18  Translation Error Type                   3177 non-null   object
 19  Tagging                                  2499 non-null   object
 20  Allocated to Reviewer?                   2419 non-null   object
 21  Author's Name                            2948 non-null   object
 22  Author Assignment Time                   833 non-null    object
 23  Author Completion Time                   784 non-null    object
 24  Author TAT (mins) [Auto]                 740 non-null    object
 25  Reviewer1 Name                           1023 non-null   object
 26  Reviewer1 Assignment Time                822 non-null    object
 27  Reviewer1 Completion Time                778 non-null    object
 28  Review1 TAT (mins) [Auto]                736 non-null    object
 29  Reviewer2 Name                           1023 non-null   object
 30  Reviewer2 Assignment Time                822 non-null    object
 31  Reviewer2 Completion Time                778 non-null    object
 32  Review2 TAT (mins) [Auto]                736 non-null    object
 33  Reviewer3 Name                           1000 non-null   object
 34  Reviewer3 Assignment Time                822 non-null    object
 35  Reviewer3 Completion Time                775 non-null    object
 36  Review3 TAT (mins) [Auto]                734 non-null    object
 37  Reviewer4 Name                           21 non-null     object
 38  Reviewer4 Assignment Time                19 non-null     object
 39  Reviewer4 Completion Time                17 non-null     object
 40  Review4 TAT (mins) [Auto]                16 non-null     object
 41  Reviewer5 Name                           8 non-null      object
 42  Reviewer5 Assignment Time                7 non-null      object
 43  Reviewer5 Completion Time                7 non-null      object
 44  Review5 TAT (mins) [Auto]                7 non-null      object
 45  Moderator's Name                         864 non-null    object
 46  Moderator Assignment Time                397 non-null    object
 47  ModeratorCompletion Time                 817 non-null    object
 48  Moderator TAT (mins) [Auto]              772 non-null    object
 49  Follow-up Q in Review Model?             2048 non-null   object
 50  Answer Scientifically Correct?           3807 non-null   object
 51  Expert Name Displayed?                   3637 non-null   object
 52  Correct Expert Name?                     3598 non-null   object
 53  Source Links Provided?                   3637 non-null   object
 54  120-min Msg Shown to User?               2254 non-null   object
 55  Notification Received?                   2093 non-null   object
 56  Notification on Same Thread?             1343 non-null   object
 57  Notification Linked Correct Q-ID?        895 non-null    object
 58  Voice Input Working?                     2777 non-null   object
 59  Voice Output Working?                    2753 non-null   object
 60  Voice Input Quality                      2791 non-null   object
 61  Voice Output Quality                     2752 non-null   object
 62  Voice Issue Description                  1998 non-null   object
 63  Weather Q Answered Correctly?            175 non-null    object
 64  Mandi Price Q Correct?                   161 non-null    object
 65  Scheme Q Correct?                        66 non-null     object
 66  Question Saved in DB?                    3694 non-null   object
 67  Answer Saved in DB?                      3394 non-null   object
 68  Q-ID Consistent Across Systems?          3375 non-null   object
 69  WhatsApp vs Web Answer Match?            1672 non-null   object
 70  Overall Test Status                      3608 non-null   object
 71  Defect Severity                          3060 non-null   object
 72  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 73  Reviewer Remarks                         3941 non-null   object
 74  Tester Remarks                           4113 non-null   object
 75  Status                                   3459 non-null   object
dtypes: datetime64[ns](1), object(75)
memory usage: 3.0+ MB

In [28]:
print(df6['Channel Tested'].unique())

['Web App' 'BOTH' 'WhatsApp' nan 'both' 'Web app' 'webapp' 'Both']

In [30]:
df6['Channel Tested'] = df6['Channel Tested'].replace(['Web app', 'webapp', 'both', 'Both', 'BOTH'], 'Web App')
print(df6['Channel Tested'].unique())

['Web App' 'WhatsApp' nan]

In [31]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 76 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5111 non-null   object
 4   Channel Tested                           5064 non-null   object
 5   Language Tested                          5093 non-null   object
 6   Question ID                              4864 non-null   object
 7   Query Text (Original)                    5111 non-null   object
 8   Question Category                        4947 non-null   object
 9   Time Question Asked (HH:MM:SS)           4934 non-null   object
 10  Time Answer Received (HH:MM:SS)          3976 non-null   object
 11  Response Time (mins) [Auto]              3612 non-null   object
 12  SLA Status                               4207 non-null   object
 13  Question in Review Model?                4272 non-null   object
 14  Question Correctly Framed?               4404 non-null   object
 15  Original Language                        4516 non-null   object
 16  Translated Language                      4217 non-null   object
 17  Translation Quality                      3611 non-null   object
 18  Translation Error Type                   3177 non-null   object
 19  Tagging                                  2499 non-null   object
 20  Allocated to Reviewer?                   2419 non-null   object
 21  Author's Name                            2948 non-null   object
 22  Author Assignment Time                   833 non-null    object
 23  Author Completion Time                   784 non-null    object
 24  Author TAT (mins) [Auto]                 740 non-null    object
 25  Reviewer1 Name                           1023 non-null   object
 26  Reviewer1 Assignment Time                822 non-null    object
 27  Reviewer1 Completion Time                778 non-null    object
 28  Review1 TAT (mins) [Auto]                736 non-null    object
 29  Reviewer2 Name                           1023 non-null   object
 30  Reviewer2 Assignment Time                822 non-null    object
 31  Reviewer2 Completion Time                778 non-null    object
 32  Review2 TAT (mins) [Auto]                736 non-null    object
 33  Reviewer3 Name                           1000 non-null   object
 34  Reviewer3 Assignment Time                822 non-null    object
 35  Reviewer3 Completion Time                775 non-null    object
 36  Review3 TAT (mins) [Auto]                734 non-null    object
 37  Reviewer4 Name                           21 non-null     object
 38  Reviewer4 Assignment Time                19 non-null     object
 39  Reviewer4 Completion Time                17 non-null     object
 40  Review4 TAT (mins) [Auto]                16 non-null     object
 41  Reviewer5 Name                           8 non-null      object
 42  Reviewer5 Assignment Time                7 non-null      object
 43  Reviewer5 Completion Time                7 non-null      object
 44  Review5 TAT (mins) [Auto]                7 non-null      object
 45  Moderator's Name                         864 non-null    object
 46  Moderator Assignment Time                397 non-null    object
 47  ModeratorCompletion Time                 817 non-null    object
 48  Moderator TAT (mins) [Auto]              772 non-null    object
 49  Follow-up Q in Review Model?             2048 non-null   object
 50  Answer Scientifically Correct?           3807 non-null   object
 51  Expert Name Displayed?                   3637 non-null   object
 52  Correct Expert Name?                     3598 non-null   object
 53  Source Links Provided?                   3637 non-null   object
 54  120-min Msg Shown to User?               2254 non-null   object
 55  Notification Received?                   2093 non-null   object
 56  Notification on Same Thread?             1343 non-null   object
 57  Notification Linked Correct Q-ID?        895 non-null    object
 58  Voice Input Working?                     2777 non-null   object
 59  Voice Output Working?                    2753 non-null   object
 60  Voice Input Quality                      2791 non-null   object
 61  Voice Output Quality                     2752 non-null   object
 62  Voice Issue Description                  1998 non-null   object
 63  Weather Q Answered Correctly?            175 non-null    object
 64  Mandi Price Q Correct?                   161 non-null    object
 65  Scheme Q Correct?                        66 non-null     object
 66  Question Saved in DB?                    3694 non-null   object
 67  Answer Saved in DB?                      3394 non-null   object
 68  Q-ID Consistent Across Systems?          3375 non-null   object
 69  WhatsApp vs Web Answer Match?            1672 non-null   object
 70  Overall Test Status                      3608 non-null   object
 71  Defect Severity                          3060 non-null   object
 72  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 73  Reviewer Remarks                         3941 non-null   object
 74  Tester Remarks                           4113 non-null   object
 75  Status                                   3459 non-null   object
dtypes: datetime64[ns](1), object(75)
memory usage: 3.0+ MB

In [32]:
df6.drop(columns=['Question ID'], inplace=True)
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 75 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5111 non-null   object
 4   Channel Tested                           5064 non-null   object
 5   Language Tested                          5093 non-null   object
 6   Query Text (Original)                    5111 non-null   object
 7   Question Category                        4947 non-null   object
 8   Time Question Asked (HH:MM:SS)           4934 non-null   object
 9   Time Answer Received (HH:MM:SS)          3976 non-null   object
 10  Response Time (mins) [Auto]              3612 non-null   object
 11  SLA Status                               4207 non-null   object
 12  Question in Review Model?                4272 non-null   object
 13  Question Correctly Framed?               4404 non-null   object
 14  Original Language                        4516 non-null   object
 15  Translated Language                      4217 non-null   object
 16  Translation Quality                      3611 non-null   object
 17  Translation Error Type                   3177 non-null   object
 18  Tagging                                  2499 non-null   object
 19  Allocated to Reviewer?                   2419 non-null   object
 20  Author's Name                            2948 non-null   object
 21  Author Assignment Time                   833 non-null    object
 22  Author Completion Time                   784 non-null    object
 23  Author TAT (mins) [Auto]                 740 non-null    object
 24  Reviewer1 Name                           1023 non-null   object
 25  Reviewer1 Assignment Time                822 non-null    object
 26  Reviewer1 Completion Time                778 non-null    object
 27  Review1 TAT (mins) [Auto]                736 non-null    object
 28  Reviewer2 Name                           1023 non-null   object
 29  Reviewer2 Assignment Time                822 non-null    object
 30  Reviewer2 Completion Time                778 non-null    object
 31  Review2 TAT (mins) [Auto]                736 non-null    object
 32  Reviewer3 Name                           1000 non-null   object
 33  Reviewer3 Assignment Time                822 non-null    object
 34  Reviewer3 Completion Time                775 non-null    object
 35  Review3 TAT (mins) [Auto]                734 non-null    object
 36  Reviewer4 Name                           21 non-null     object
 37  Reviewer4 Assignment Time                19 non-null     object
 38  Reviewer4 Completion Time                17 non-null     object
 39  Review4 TAT (mins) [Auto]                16 non-null     object
 40  Reviewer5 Name                           8 non-null      object
 41  Reviewer5 Assignment Time                7 non-null      object
 42  Reviewer5 Completion Time                7 non-null      object
 43  Review5 TAT (mins) [Auto]                7 non-null      object
 44  Moderator's Name                         864 non-null    object
 45  Moderator Assignment Time                397 non-null    object
 46  ModeratorCompletion Time                 817 non-null    object
 47  Moderator TAT (mins) [Auto]              772 non-null    object
 48  Follow-up Q in Review Model?             2048 non-null   object
 49  Answer Scientifically Correct?           3807 non-null   object
 50  Expert Name Displayed?                   3637 non-null   object
 51  Correct Expert Name?                     3598 non-null   object
 52  Source Links Provided?                   3637 non-null   object
 53  120-min Msg Shown to User?               2254 non-null   object
 54  Notification Received?                   2093 non-null   object
 55  Notification on Same Thread?             1343 non-null   object
 56  Notification Linked Correct Q-ID?        895 non-null    object
 57  Voice Input Working?                     2777 non-null   object
 58  Voice Output Working?                    2753 non-null   object
 59  Voice Input Quality                      2791 non-null   object
 60  Voice Output Quality                     2752 non-null   object
 61  Voice Issue Description                  1998 non-null   object
 62  Weather Q Answered Correctly?            175 non-null    object
 63  Mandi Price Q Correct?                   161 non-null    object
 64  Scheme Q Correct?                        66 non-null     object
 65  Question Saved in DB?                    3694 non-null   object
 66  Answer Saved in DB?                      3394 non-null   object
 67  Q-ID Consistent Across Systems?          3375 non-null   object
 68  WhatsApp vs Web Answer Match?            1672 non-null   object
 69  Overall Test Status                      3608 non-null   object
 70  Defect Severity                          3060 non-null   object
 71  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 72  Reviewer Remarks                         3941 non-null   object
 73  Tester Remarks                           4113 non-null   object
 74  Status                                   3459 non-null   object
dtypes: datetime64[ns](1), object(74)
memory usage: 2.9+ MB

In [33]:
df6.to_csv("Checkpoint2.csv", index = False)

In [34]:
df6['Time Question Asked (HH:MM:SS)_temp'] = pd.to_datetime(df6['Time Question Asked (HH:MM:SS)'], format='%H:%M:%S', errors='coerce').dt.time
display(df6.head())
df6.info()

,Test ID,Test Date,Tester Name,Build / Version,Channel Tested,Language Tested,Query Text (Original),Question Category,Time Question Asked (HH:MM:SS),Time Answer Received (HH:MM:SS),...,Answer Saved in DB?,Q-ID Consistent Across Systems?,WhatsApp vs Web Answer Match?,Overall Test Status,Defect Severity,Defect ID / Bug Ref\nZoho Desk Ticketing,Reviewer Remarks,Tester Remarks,Status,Time Question Asked (HH:MM:SS)_temp
0,1,2026-06-08,Souvik Roy,0.1,Web App,English,How to control Dila in Paddy?,Plant Protection,2:32:32 PM,2:32:40 PM,...,Duplicate,Successfully Identified as Duplicate,NaN,Pass,Low,https://desk.zoho.in/agent/annamai/annam-ai/ti...,NIL,"District names appeared as ""ALL"", it should ha...",NaN,NaT
1,TL-0007,2026-06-08,T.Vishnu Vardhan,0.1,Web App,English,Which varieties of chilli are most suitable fo...,Cultural and Crop Management Practices,06:52:AM,NaN,...,NaN,Successfully Identified as Duplicate,NaN,NaN,NaN,NaN,NIL,2 hours disclaimer is seen,NaN,NaT
2,2,2026-06-08,Nimisha,0.1,Web App,English,What are the primary causes of stunted growth ...,Plant Protection,16:25:18,16:25:28,...,Duplicate,Successfully Identified as Duplicate,NaN,Pass,NO Defect,NaN,NIL,"for longer text, audio output takes more time",NaN,16:25:18
3,TL-0065,2026-06-09,Lavanya Mathialagan,0.1,Web App,English,\r\nHow can fish amino acids be prepared and u...,Organic and Natural Farming,19:14:00,NaN,...,NaN,Successfully Identified as Duplicate,NaN,NaN,NaN,NaN,NIL,2 Hours disclaimer is seen. Even after 2 hours...,NaN,19:14:00
4,TL-0009,2026-06-09,JOYDEEP,0.1,Web App,English,What is the correct method and procedure for p...,Soil Health and Nutrient Management,10.52.00,6.21am,...,Saved,Successfully Identified as Duplicate,Yes,Pass,NaN,NaN,NIL,"District names appeared as ""ALL"", it should ha...",NaN,NaT

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 76 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5111 non-null   object
 4   Channel Tested                           5064 non-null   object
 5   Language Tested                          5093 non-null   object
 6   Query Text (Original)                    5111 non-null   object
 7   Question Category                        4947 non-null   object
 8   Time Question Asked (HH:MM:SS)           4934 non-null   object
 9   Time Answer Received (HH:MM:SS)          3976 non-null   object
 10  Response Time (mins) [Auto]              3612 non-null   object
 11  SLA Status                               4207 non-null   object
 12  Question in Review Model?                4272 non-null   object
 13  Question Correctly Framed?               4404 non-null   object
 14  Original Language                        4516 non-null   object
 15  Translated Language                      4217 non-null   object
 16  Translation Quality                      3611 non-null   object
 17  Translation Error Type                   3177 non-null   object
 18  Tagging                                  2499 non-null   object
 19  Allocated to Reviewer?                   2419 non-null   object
 20  Author's Name                            2948 non-null   object
 21  Author Assignment Time                   833 non-null    object
 22  Author Completion Time                   784 non-null    object
 23  Author TAT (mins) [Auto]                 740 non-null    object
 24  Reviewer1 Name                           1023 non-null   object
 25  Reviewer1 Assignment Time                822 non-null    object
 26  Reviewer1 Completion Time                778 non-null    object
 27  Review1 TAT (mins) [Auto]                736 non-null    object
 28  Reviewer2 Name                           1023 non-null   object
 29  Reviewer2 Assignment Time                822 non-null    object
 30  Reviewer2 Completion Time                778 non-null    object
 31  Review2 TAT (mins) [Auto]                736 non-null    object
 32  Reviewer3 Name                           1000 non-null   object
 33  Reviewer3 Assignment Time                822 non-null    object
 34  Reviewer3 Completion Time                775 non-null    object
 35  Review3 TAT (mins) [Auto]                734 non-null    object
 36  Reviewer4 Name                           21 non-null     object
 37  Reviewer4 Assignment Time                19 non-null     object
 38  Reviewer4 Completion Time                17 non-null     object
 39  Review4 TAT (mins) [Auto]                16 non-null     object
 40  Reviewer5 Name                           8 non-null      object
 41  Reviewer5 Assignment Time                7 non-null      object
 42  Reviewer5 Completion Time                7 non-null      object
 43  Review5 TAT (mins) [Auto]                7 non-null      object
 44  Moderator's Name                         864 non-null    object
 45  Moderator Assignment Time                397 non-null    object
 46  ModeratorCompletion Time                 817 non-null    object
 47  Moderator TAT (mins) [Auto]              772 non-null    object
 48  Follow-up Q in Review Model?             2048 non-null   object
 49  Answer Scientifically Correct?           3807 non-null   object
 50  Expert Name Displayed?                   3637 non-null   object
 51  Correct Expert Name?                     3598 non-null   object
 52  Source Links Provided?                   3637 non-null   object
 53  120-min Msg Shown to User?               2254 non-null   object
 54  Notification Received?                   2093 non-null   object
 55  Notification on Same Thread?             1343 non-null   object
 56  Notification Linked Correct Q-ID?        895 non-null    object
 57  Voice Input Working?                     2777 non-null   object
 58  Voice Output Working?                    2753 non-null   object
 59  Voice Input Quality                      2791 non-null   object
 60  Voice Output Quality                     2752 non-null   object
 61  Voice Issue Description                  1998 non-null   object
 62  Weather Q Answered Correctly?            175 non-null    object
 63  Mandi Price Q Correct?                   161 non-null    object
 64  Scheme Q Correct?                        66 non-null     object
 65  Question Saved in DB?                    3694 non-null   object
 66  Answer Saved in DB?                      3394 non-null   object
 67  Q-ID Consistent Across Systems?          3375 non-null   object
 68  WhatsApp vs Web Answer Match?            1672 non-null   object
 69  Overall Test Status                      3608 non-null   object
 70  Defect Severity                          3060 non-null   object
 71  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 72  Reviewer Remarks                         3941 non-null   object
 73  Tester Remarks                           4113 non-null   object
 74  Status                                   3459 non-null   object
 75  Time Question Asked (HH:MM:SS)_temp      4111 non-null   object
dtypes: datetime64[ns](1), object(75)
memory usage: 3.0+ MB

In [35]:
selected_column_indices = [8, 9, 10, 21, 22, 23, 25, 26, 27, 29, 30, 31, 33, 34, 35, 37, 38, 39, 41, 42, 43, 45, 46, 47]
selected_column_names = df6.columns[selected_column_indices].tolist()
df_selected_columns = df6[selected_column_names]
df_selected_columns.to_csv("selected_columns.csv", index=False)
print("New CSV file 'selected_columns.csv' created successfully with the requested columns.")

New CSV file 'selected_columns.csv' created successfully with the requested columns.

In [38]:
new_selected_column_indices = [8, 9, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
new_selected_column_names = df6.columns[new_selected_column_indices].tolist()
df_new_selected_columns = df6[new_selected_column_names]
df_new_selected_columns.to_csv("selected_columns_new.csv", index=False)
print("New CSV file 'selected_columns_new.csv' created successfully with the requested columns.")
display(df_new_selected_columns.head())
df_new_selected_columns.info()

New CSV file 'selected_columns_new.csv' created successfully with the requested columns.

,Time Question Asked (HH:MM:SS),Time Answer Received (HH:MM:SS),Response Time (mins) [Auto],Author's Name,Author Assignment Time,Author Completion Time,Author TAT (mins) [Auto],Reviewer1 Name,Reviewer1 Assignment Time,Reviewer1 Completion Time,...,Reviewer4 Completion Time,Review4 TAT (mins) [Auto],Reviewer5 Name,Reviewer5 Assignment Time,Reviewer5 Completion Time,Review5 TAT (mins) [Auto],Moderator's Name,Moderator Assignment Time,ModeratorCompletion Time,Moderator TAT (mins) [Auto]
0,2:32:32 PM,2:32:40 PM,00:00:08,Salim Sahaji,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,06:52:AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16:25:18,16:25:28,0.2,Divyadarshni K,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19:14:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10.52.00,6.21am,#VALUE!,Sanjay Choudhary,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Time Question Asked (HH:MM:SS)   4934 non-null   object
 1   Time Answer Received (HH:MM:SS)  3976 non-null   object
 2   Response Time (mins) [Auto]      3612 non-null   object
 3   Author's Name                    2948 non-null   object
 4   Author Assignment Time           833 non-null    object
 5   Author Completion Time           784 non-null    object
 6   Author TAT (mins) [Auto]         740 non-null    object
 7   Reviewer1 Name                   1023 non-null   object
 8   Reviewer1 Assignment Time        822 non-null    object
 9   Reviewer1 Completion Time        778 non-null    object
 10  Review1 TAT (mins) [Auto]        736 non-null    object
 11  Reviewer2 Name                   1023 non-null   object
 12  Reviewer2 Assignment Time        822 non-null    object
 13  Reviewer2 Completion Time        778 non-null    object
 14  Review2 TAT (mins) [Auto]        736 non-null    object
 15  Reviewer3 Name                   1000 non-null   object
 16  Reviewer3 Assignment Time        822 non-null    object
 17  Reviewer3 Completion Time        775 non-null    object
 18  Review3 TAT (mins) [Auto]        734 non-null    object
 19  Reviewer4 Name                   21 non-null     object
 20  Reviewer4 Assignment Time        19 non-null     object
 21  Reviewer4 Completion Time        17 non-null     object
 22  Review4 TAT (mins) [Auto]        16 non-null     object
 23  Reviewer5 Name                   8 non-null      object
 24  Reviewer5 Assignment Time        7 non-null      object
 25  Reviewer5 Completion Time        7 non-null      object
 26  Review5 TAT (mins) [Auto]        7 non-null      object
 27  Moderator's Name                 864 non-null    object
 28  Moderator Assignment Time        397 non-null    object
 29  ModeratorCompletion Time         817 non-null    object
 30  Moderator TAT (mins) [Auto]      772 non-null    object
dtypes: object(31)
memory usage: 1.2+ MB

In [39]:
print(df6['SLA Status'].unique())

['Within SLA' nan 'SLA Breached' 'Not Applicable' 'SLA Breachd' '\\'
 'SLA breached' 'Within the SLA' 'Breached SLA' 'WITHIN SLA' 'WITHIN SLA '
 'within SLA']

In [40]:
df6['SLA Status'] = df6['SLA Status'].replace({
    'Within the SLA': 'Within SLA',
    'WITHIN SLA': 'Within SLA',
    'WITHIN SLA ': 'Within SLA',
    'within SLA': 'Within SLA',
    'SLA Breachd': 'SLA Breached',
    'SLA breached': 'SLA Breached',
    'Breached SLA': 'SLA Breached',
    '\\': 'Not Applicable' # Assuming '\' is a typo for breached
})

# Convert any remaining NaN values to 'Not Applicable'
df6['SLA Status'] = df6['SLA Status'].fillna('Not Applicable')

print(df6['SLA Status'].unique())

['Within SLA' 'Not Applicable' 'SLA Breached']

In [41]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 76 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5111 non-null   object
 4   Channel Tested                           5064 non-null   object
 5   Language Tested                          5093 non-null   object
 6   Query Text (Original)                    5111 non-null   object
 7   Question Category                        4947 non-null   object
 8   Time Question Asked (HH:MM:SS)           4934 non-null   object
 9   Time Answer Received (HH:MM:SS)          3976 non-null   object
 10  Response Time (mins) [Auto]              3612 non-null   object
 11  SLA Status                               5111 non-null   object
 12  Question in Review Model?                4272 non-null   object
 13  Question Correctly Framed?               4404 non-null   object
 14  Original Language                        4516 non-null   object
 15  Translated Language                      4217 non-null   object
 16  Translation Quality                      3611 non-null   object
 17  Translation Error Type                   3177 non-null   object
 18  Tagging                                  2499 non-null   object
 19  Allocated to Reviewer?                   2419 non-null   object
 20  Author's Name                            2948 non-null   object
 21  Author Assignment Time                   833 non-null    object
 22  Author Completion Time                   784 non-null    object
 23  Author TAT (mins) [Auto]                 740 non-null    object
 24  Reviewer1 Name                           1023 non-null   object
 25  Reviewer1 Assignment Time                822 non-null    object
 26  Reviewer1 Completion Time                778 non-null    object
 27  Review1 TAT (mins) [Auto]                736 non-null    object
 28  Reviewer2 Name                           1023 non-null   object
 29  Reviewer2 Assignment Time                822 non-null    object
 30  Reviewer2 Completion Time                778 non-null    object
 31  Review2 TAT (mins) [Auto]                736 non-null    object
 32  Reviewer3 Name                           1000 non-null   object
 33  Reviewer3 Assignment Time                822 non-null    object
 34  Reviewer3 Completion Time                775 non-null    object
 35  Review3 TAT (mins) [Auto]                734 non-null    object
 36  Reviewer4 Name                           21 non-null     object
 37  Reviewer4 Assignment Time                19 non-null     object
 38  Reviewer4 Completion Time                17 non-null     object
 39  Review4 TAT (mins) [Auto]                16 non-null     object
 40  Reviewer5 Name                           8 non-null      object
 41  Reviewer5 Assignment Time                7 non-null      object
 42  Reviewer5 Completion Time                7 non-null      object
 43  Review5 TAT (mins) [Auto]                7 non-null      object
 44  Moderator's Name                         864 non-null    object
 45  Moderator Assignment Time                397 non-null    object
 46  ModeratorCompletion Time                 817 non-null    object
 47  Moderator TAT (mins) [Auto]              772 non-null    object
 48  Follow-up Q in Review Model?             2048 non-null   object
 49  Answer Scientifically Correct?           3807 non-null   object
 50  Expert Name Displayed?                   3637 non-null   object
 51  Correct Expert Name?                     3598 non-null   object
 52  Source Links Provided?                   3637 non-null   object
 53  120-min Msg Shown to User?               2254 non-null   object
 54  Notification Received?                   2093 non-null   object
 55  Notification on Same Thread?             1343 non-null   object
 56  Notification Linked Correct Q-ID?        895 non-null    object
 57  Voice Input Working?                     2777 non-null   object
 58  Voice Output Working?                    2753 non-null   object
 59  Voice Input Quality                      2791 non-null   object
 60  Voice Output Quality                     2752 non-null   object
 61  Voice Issue Description                  1998 non-null   object
 62  Weather Q Answered Correctly?            175 non-null    object
 63  Mandi Price Q Correct?                   161 non-null    object
 64  Scheme Q Correct?                        66 non-null     object
 65  Question Saved in DB?                    3694 non-null   object
 66  Answer Saved in DB?                      3394 non-null   object
 67  Q-ID Consistent Across Systems?          3375 non-null   object
 68  WhatsApp vs Web Answer Match?            1672 non-null   object
 69  Overall Test Status                      3608 non-null   object
 70  Defect Severity                          3060 non-null   object
 71  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 72  Reviewer Remarks                         3941 non-null   object
 73  Tester Remarks                           4113 non-null   object
 74  Status                                   3459 non-null   object
 75  Time Question Asked (HH:MM:SS)_temp      4111 non-null   object
dtypes: datetime64[ns](1), object(75)
memory usage: 3.0+ MB

In [42]:
df6.drop(columns=['Translation Error Type'], inplace=True)
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 75 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5111 non-null   object
 4   Channel Tested                           5064 non-null   object
 5   Language Tested                          5093 non-null   object
 6   Query Text (Original)                    5111 non-null   object
 7   Question Category                        4947 non-null   object
 8   Time Question Asked (HH:MM:SS)           4934 non-null   object
 9   Time Answer Received (HH:MM:SS)          3976 non-null   object
 10  Response Time (mins) [Auto]              3612 non-null   object
 11  SLA Status                               5111 non-null   object
 12  Question in Review Model?                4272 non-null   object
 13  Question Correctly Framed?               4404 non-null   object
 14  Original Language                        4516 non-null   object
 15  Translated Language                      4217 non-null   object
 16  Translation Quality                      3611 non-null   object
 17  Tagging                                  2499 non-null   object
 18  Allocated to Reviewer?                   2419 non-null   object
 19  Author's Name                            2948 non-null   object
 20  Author Assignment Time                   833 non-null    object
 21  Author Completion Time                   784 non-null    object
 22  Author TAT (mins) [Auto]                 740 non-null    object
 23  Reviewer1 Name                           1023 non-null   object
 24  Reviewer1 Assignment Time                822 non-null    object
 25  Reviewer1 Completion Time                778 non-null    object
 26  Review1 TAT (mins) [Auto]                736 non-null    object
 27  Reviewer2 Name                           1023 non-null   object
 28  Reviewer2 Assignment Time                822 non-null    object
 29  Reviewer2 Completion Time                778 non-null    object
 30  Review2 TAT (mins) [Auto]                736 non-null    object
 31  Reviewer3 Name                           1000 non-null   object
 32  Reviewer3 Assignment Time                822 non-null    object
 33  Reviewer3 Completion Time                775 non-null    object
 34  Review3 TAT (mins) [Auto]                734 non-null    object
 35  Reviewer4 Name                           21 non-null     object
 36  Reviewer4 Assignment Time                19 non-null     object
 37  Reviewer4 Completion Time                17 non-null     object
 38  Review4 TAT (mins) [Auto]                16 non-null     object
 39  Reviewer5 Name                           8 non-null      object
 40  Reviewer5 Assignment Time                7 non-null      object
 41  Reviewer5 Completion Time                7 non-null      object
 42  Review5 TAT (mins) [Auto]                7 non-null      object
 43  Moderator's Name                         864 non-null    object
 44  Moderator Assignment Time                397 non-null    object
 45  ModeratorCompletion Time                 817 non-null    object
 46  Moderator TAT (mins) [Auto]              772 non-null    object
 47  Follow-up Q in Review Model?             2048 non-null   object
 48  Answer Scientifically Correct?           3807 non-null   object
 49  Expert Name Displayed?                   3637 non-null   object
 50  Correct Expert Name?                     3598 non-null   object
 51  Source Links Provided?                   3637 non-null   object
 52  120-min Msg Shown to User?               2254 non-null   object
 53  Notification Received?                   2093 non-null   object
 54  Notification on Same Thread?             1343 non-null   object
 55  Notification Linked Correct Q-ID?        895 non-null    object
 56  Voice Input Working?                     2777 non-null   object
 57  Voice Output Working?                    2753 non-null   object
 58  Voice Input Quality                      2791 non-null   object
 59  Voice Output Quality                     2752 non-null   object
 60  Voice Issue Description                  1998 non-null   object
 61  Weather Q Answered Correctly?            175 non-null    object
 62  Mandi Price Q Correct?                   161 non-null    object
 63  Scheme Q Correct?                        66 non-null     object
 64  Question Saved in DB?                    3694 non-null   object
 65  Answer Saved in DB?                      3394 non-null   object
 66  Q-ID Consistent Across Systems?          3375 non-null   object
 67  WhatsApp vs Web Answer Match?            1672 non-null   object
 68  Overall Test Status                      3608 non-null   object
 69  Defect Severity                          3060 non-null   object
 70  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 71  Reviewer Remarks                         3941 non-null   object
 72  Tester Remarks                           4113 non-null   object
 73  Status                                   3459 non-null   object
 74  Time Question Asked (HH:MM:SS)_temp      4111 non-null   object
dtypes: datetime64[ns](1), object(74)
memory usage: 2.9+ MB

In [43]:
print("Unique values for 'Question in Review Model?':", df6['Question in Review Model?'].unique())
print("Unique values for 'Question Correctly Framed?':", df6['Question Correctly Framed?'].unique())
print("Unique values for 'Original Language':", df6['Original Language'].unique())
print("Unique values for 'Translated Language':", df6['Translated Language'].unique())
print("Unique values for 'Translation Quality':", df6['Translation Quality'].unique())
print("Unique values for 'Tagging':", df6['Tagging'].unique())
print("Unique values for 'Allocated to Reviewer?':", df6['Allocated to Reviewer?'].unique())

Unique values for 'Question in Review Model?': ['Yes' nan 'Successfully Identified as Duplicate'
 'correctly identified as duplicate' 'No'
 'Wrongly Identified as Duplicate' 'no' 'yes']
Unique values for 'Question Correctly Framed?': ['Well Framed' nan 'Ambiguous' 'Incorrectly Framed' 'Yes']
Unique values for 'Original Language': ['English' nan 'Telugu' 'Bengali' 'Tamil' 'ENGLISH' 'BENGALI' 'Hindi'
 'ENGLISH ' 'english' 'Englsih' 'ENG;ISH']
Unique values for 'Translated Language': ['English' nan 'Tamil' 'Marathi' 'Hindi' 'Other' 'Telugu' 'Bengali'
 'ENGLISH' 'E']
Unique values for 'Translation Quality': ['Correct' nan 'Major Error' 'Minor Error' 'good' 'correct' 'Good' 'N A'
 'GOOD' 'CORRECT' 'Incorrect' 'Wrong' 'NIL'
 'Not able trnaslate disease word in telugu(తెగుళ్ల)']
Unique values for 'Tagging': ['Correctly Tagged as Duplicate' nan 'Dynamic but not tagged'
 'Wrongly Tagged as Duplicate' 'Duplicate but not tagged'
 'Correctly Tagged as Dynamic' 'Wrongly Tagged as Dynamic' 'DYNAMIC'
 'Correctly tagged as duplicate']
Unique values for 'Allocated to Reviewer?': ['Successfully Identified as Duplicate/Dynamic' nan 'Yes' 'No' 'NIL'
 'Correct' 'NO' 'yes' 'YES' 'Wrongly Identified as Duplicate/Dynamic'
 'Correctly Tagged as Duplicate' 'Yes ' 'na' 'no'
 'Wrongly Tagged as Duplicate' 'Duplicate' 'Duplicate but not tagged'
 'MONICA M' 'Girishma Gonnabathula' 'C Sai Durga' 'Utkarsh Singh Vishen'
 'pooja soni' 'Tejas Dange' 'Shivendra Pratap Singh' 'Pallavi J P'
 'Rajwant kaur' 'Anmol kaundal' 'Salim Sahaji' 'Kavya Ponugoti'
 'Khaja Suhaib .' 'Yash Praveen Khot' 'satarupa saha' 'NO ' 'Not yet']

In [45]:
# Normalize 'Question in Review Model?'
df6['Question in Review Model?'] = df6['Question in Review Model?'].replace({
    'Successfully Identified as Duplicate': 'Yes',
    'correctly identified as duplicate': 'Yes',
    'Wrongly Identified as Duplicate': 'No',
    'no': 'No',
    'yes': 'Yes'
}).fillna('Not Applicable')
df6['Question in Review Model?'] = df6['Question in Review Model?'].str.strip()

# Normalize 'Question Correctly Framed?'
df6['Question Correctly Framed?'] = df6['Question Correctly Framed?'].replace({
    'Well Framed': 'Yes',
    'Ambiguous': 'No',
    'Incorrectly Framed': 'No'
}).fillna('Not Applicable')
df6['Question Correctly Framed?'] = df6['Question Correctly Framed?'].str.strip()

# Normalize 'Original Language'
df6['Original Language'] = df6['Original Language'].replace({
    'ENGLISH': 'English',
    'ENGLISH ': 'English',
    'english': 'English',
    'Englsih': 'English',
    'ENG;ISH': 'English',
    'BENGALI': 'Bengali'
}).fillna('Not Specified')
df6['Original Language'] = df6['Original Language'].str.strip()

# Normalize 'Translated Language'
df6['Translated Language'] = df6['Translated Language'].replace({
    'ENGLISH': 'English',
    'E': 'English'
}).fillna('Not Specified')
df6['Translated Language'] = df6['Translated Language'].str.strip()

# Normalize 'Translation Quality'
df6['Translation Quality'] = df6['Translation Quality'].replace({
    'Correct': 'Good', # Added this mapping
    'good': 'Good',
    'correct': 'Good',
    'GOOD': 'Good',
    'CORRECT': 'Good',
    'Major Error': 'Poor', # Added this mapping
    'Minor Error': 'Poor', # Added this mapping
    'Incorrect': 'Poor',
    'Wrong': 'Poor',
    'Not able trnaslate disease word in telugu(తెగుళ్ల)': 'Poor',
    'N A': 'Not Applicable',
    'NIL': 'Not Applicable'
}).fillna('Not Applicable')
df6['Translation Quality'] = df6['Translation Quality'].str.strip()

# Normalize 'Tagging'
df6['Tagging'] = df6['Tagging'].replace({
    'Correctly tagged as duplicate': 'Correctly Tagged as Duplicate',
    'Dynamic but not tagged': 'Not Tagged',
    'Duplicate but not tagged': 'Not Tagged',
    'Wrongly Tagged as Duplicate': 'Wrongly Tagged',
    'Wrongly Tagged as Dynamic': 'Wrongly Tagged',
    'DYNAMIC': 'Correctly Tagged as Dynamic'
}).fillna('Not Applicable')
df6['Tagging'] = df6['Tagging'].str.strip()

# Normalize 'Allocated to Reviewer?'
# First, identify reviewer names. Assuming any string not explicitly 'Yes', 'No', 'NIL', 'na', 'Not Applicable' is a name.
reviewer_names = df6['Allocated to Reviewer?'].unique()
reviewer_names_to_yes = [name for name in reviewer_names if isinstance(name, str) and name not in ['Yes', 'No', 'NIL', 'na', 'NO', 'yes', 'YES', 'Yes ', 'no', 'NO ', 'Not yet', 'Correct', 'Successfully Identified as Duplicate/Dynamic', 'Correctly Tagged as Duplicate', 'Wrongly Identified as Duplicate/Dynamic', 'Wrongly Tagged as Duplicate', 'Duplicate', 'Duplicate but not tagged']]

df6['Allocated to Reviewer?'] = df6['Allocated to Reviewer?'].replace({
    'Successfully Identified as Duplicate/Dynamic': 'Yes',
    'Correctly Tagged as Duplicate': 'Yes',
    'Wrongly Identified as Duplicate/Dynamic': 'No',
    'Wrongly Tagged as Duplicate': 'No',
    'Duplicate': 'Yes', # Assuming 'Duplicate' means it was allocated for review as a duplicate
    'Duplicate but not tagged': 'No', # Not allocated if not tagged
    'yes': 'Yes',
    'YES': 'Yes',
    'Yes ': 'Yes',
    'NO': 'No',
    'no': 'No',
    'NO ': 'No',
    'Not yet': 'No',
    'Correct': 'Yes',
    'NIL': 'Not Applicable',
    'na': 'Not Applicable',
    **{name: 'Yes' for name in reviewer_names_to_yes}
}).fillna('Not Applicable')
df6['Allocated to Reviewer?'] = df6['Allocated to Reviewer?'].str.strip()


# Display unique values to confirm normalization
print("Normalized unique values for 'Question in Review Model?':", df6['Question in Review Model?'].unique())
print("Normalized unique values for 'Question Correctly Framed?':", df6['Question Correctly Framed?'].unique())
print("Normalized unique values for 'Original Language':", df6['Original Language'].unique())
print("Normalized unique values for 'Translated Language':", df6['Translated Language'].unique())
print("Normalized unique values for 'Translation Quality':", df6['Translation Quality'].unique())
print("Normalized unique values for 'Tagging':", df6['Tagging'].unique())
print("Normalized unique values for 'Allocated to Reviewer?':", df6['Allocated to Reviewer?'].unique())

Normalized unique values for 'Question in Review Model?': ['Yes' 'Not Applicable' 'No']
Normalized unique values for 'Question Correctly Framed?': ['Yes' 'Not Applicable' 'No']
Normalized unique values for 'Original Language': ['English' 'Not Specified' 'Telugu' 'Bengali' 'Tamil' 'Hindi']
Normalized unique values for 'Translated Language': ['English' 'Not Specified' 'Tamil' 'Marathi' 'Hindi' 'Other' 'Telugu'
 'Bengali']
Normalized unique values for 'Translation Quality': ['Good' 'Not Applicable' 'Poor']
Normalized unique values for 'Tagging': ['Correctly Tagged as Duplicate' 'Not Applicable' 'Not Tagged'
 'Wrongly Tagged' 'Correctly Tagged as Dynamic']
Normalized unique values for 'Allocated to Reviewer?': ['Yes' 'No']

In [47]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 75 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Test ID                                  5111 non-null   object
 1   Test Date                                5111 non-null   datetime64[ns]
 2   Tester Name                              5111 non-null   object
 3   Build / Version                          5111 non-null   object
 4   Channel Tested                           5064 non-null   object
 5   Language Tested                          5093 non-null   object
 6   Query Text (Original)                    5111 non-null   object
 7   Question Category                        4947 non-null   object
 8   Time Question Asked (HH:MM:SS)           4934 non-null   object
 9   Time Answer Received (HH:MM:SS)          3976 non-null   object
 10  Response Time (mins) [Auto]              3612 non-null   object
 11  SLA Status                               5111 non-null   object
 12  Question in Review Model?                5111 non-null   object
 13  Question Correctly Framed?               5111 non-null   object
 14  Original Language                        5111 non-null   object
 15  Translated Language                      5111 non-null   object
 16  Translation Quality                      5111 non-null   object
 17  Tagging                                  5111 non-null   object
 18  Allocated to Reviewer?                   5111 non-null   object
 19  Author's Name                            2948 non-null   object
 20  Author Assignment Time                   833 non-null    object
 21  Author Completion Time                   784 non-null    object
 22  Author TAT (mins) [Auto]                 740 non-null    object
 23  Reviewer1 Name                           1023 non-null   object
 24  Reviewer1 Assignment Time                822 non-null    object
 25  Reviewer1 Completion Time                778 non-null    object
 26  Review1 TAT (mins) [Auto]                736 non-null    object
 27  Reviewer2 Name                           1023 non-null   object
 28  Reviewer2 Assignment Time                822 non-null    object
 29  Reviewer2 Completion Time                778 non-null    object
 30  Review2 TAT (mins) [Auto]                736 non-null    object
 31  Reviewer3 Name                           1000 non-null   object
 32  Reviewer3 Assignment Time                822 non-null    object
 33  Reviewer3 Completion Time                775 non-null    object
 34  Review3 TAT (mins) [Auto]                734 non-null    object
 35  Reviewer4 Name                           21 non-null     object
 36  Reviewer4 Assignment Time                19 non-null     object
 37  Reviewer4 Completion Time                17 non-null     object
 38  Review4 TAT (mins) [Auto]                16 non-null     object
 39  Reviewer5 Name                           8 non-null      object
 40  Reviewer5 Assignment Time                7 non-null      object
 41  Reviewer5 Completion Time                7 non-null      object
 42  Review5 TAT (mins) [Auto]                7 non-null      object
 43  Moderator's Name                         864 non-null    object
 44  Moderator Assignment Time                397 non-null    object
 45  ModeratorCompletion Time                 817 non-null    object
 46  Moderator TAT (mins) [Auto]              772 non-null    object
 47  Follow-up Q in Review Model?             2048 non-null   object
 48  Answer Scientifically Correct?           3807 non-null   object
 49  Expert Name Displayed?                   3637 non-null   object
 50  Correct Expert Name?                     3598 non-null   object
 51  Source Links Provided?                   3637 non-null   object
 52  120-min Msg Shown to User?               2254 non-null   object
 53  Notification Received?                   2093 non-null   object
 54  Notification on Same Thread?             1343 non-null   object
 55  Notification Linked Correct Q-ID?        895 non-null    object
 56  Voice Input Working?                     2777 non-null   object
 57  Voice Output Working?                    2753 non-null   object
 58  Voice Input Quality                      2791 non-null   object
 59  Voice Output Quality                     2752 non-null   object
 60  Voice Issue Description                  1998 non-null   object
 61  Weather Q Answered Correctly?            175 non-null    object
 62  Mandi Price Q Correct?                   161 non-null    object
 63  Scheme Q Correct?                        66 non-null     object
 64  Question Saved in DB?                    3694 non-null   object
 65  Answer Saved in DB?                      3394 non-null   object
 66  Q-ID Consistent Across Systems?          3375 non-null   object
 67  WhatsApp vs Web Answer Match?            1672 non-null   object
 68  Overall Test Status                      3608 non-null   object
 69  Defect Severity                          3060 non-null   object
 70  Defect ID / Bug Ref
Zoho Desk Ticketing  1573 non-null   object
 71  Reviewer Remarks                         3941 non-null   object
 72  Tester Remarks                           4113 non-null   object
 73  Status                                   3459 non-null   object
 74  Time Question Asked (HH:MM:SS)_temp      4111 non-null   object
dtypes: datetime64[ns](1), object(74)
memory usage: 2.9+ MB